---
title: "Atrial Septal Defect"
author: "Dr Samuel Blay Nguah"
---

## 

## Introducion

1.  Defect in the inter-atrial septum
2.  5-10% of all CHD
3.  Types
    -   Secundum ASD (most common, 50-70%)
    -   Primum ASD (30%)
    -   Sinus venosus ASD
    -   Coronary sinus ASD

## Pathophysiology

-   Left to right shunting and thus acyanotic
-   leads to volume overload of the right atrium, ventricle, pulmonary artery and pulmonary oedema
-   Consequent dilatation of the right atrium and ventricles
-   Minimal pressure transmitted so no significant pressure overload
-   Consequently, pulmonary oedema is usually insignificant
-   Rarely have overt heart failure
-   However, long-standing liaison or a very big lesion with a pulmonary-to-systemic flow ratio of 2
    or more will lead to heart failure and pulmonary hypertension after about 15 to 20 years No
    Reversal of shunt

## Clinical presentatoin

-   Usually asymptomatic except for big lesion with high Qp: Qs
-   They often have slender bodies
-   Auscultation reveals a widely fixed split-second heart sound and a grade 2/6 to 3/6 ejection
    systolic murmur at the upper sternal border
-   Many are almost silent, especially the small lesions which are often detected during an
    echocardiogram for another reason

## Investigations

-   Bedside SpO2 is usually normal and hence an acyanotic heart disease
-   In older patients, a chest x-ray may show
    -   Cardiomegaly
    -   Prominent pulmonary artery
    -   Increased vascular markings
-   The electrocardiogram may show
    -   Right axis deviation due to the right ventricular dilatation
    -   Right atrial enlargement
-   An echocardiogram is diagnostic as it visualises the defect, and quantifies the shunt and other
    chamber sizes.
-   Cardiac catheterization is often done in long-standing cases to detect complications that may
    have arisen.

## Natural history

-   Most ASDs will close spontaneously by 4 years, with smaller ones having a higher closure rate
    than bigger ones. A long-standing large defect however leads to chronic heart failure and
    pulmonary hypertension in early adulthood.
-   Arrhythmias may arise because of the dilated right atrium.
-   Though there are reported cases of paradoxical strokes in patients with ASDs, it remains an
    uncommon occurrence.
-   Infective endocarditis is also rare in ASDs.

## Treatment

There is no need for exercise restriction or prophylaxis for endocarditis. If there is no sign of
heart failure, a device closure is often done after infancy or a surgical closure at 2-4 years of
age. However, if there is heart failure, Medical treatment for heart failure is immediately
instituted. Then a planned device closure or surgical closure can be done within the first year of
life.

## Prognosis

Prognosis is generally good with many living into adulthood even without corrective surgery.
Post-surgical mortality i currently less the 0.5%. The patient will need very little long-term
follow-up after the corrective surgery.
