---
title: "Cardiovascular Dysfunction"
author: "Dr John Adabie Appiah"
editor: 
  markdown: 
    wrap: sentence
---

## Background

In resource-limited resource settings, such as those lacking access to healthcare staff, equipment, and resources, pediatric emergency and critical care (PECC) play an essential role.
These settings bear the highest burden of severe acute illness and life-threatening injuries.
Still, due to underappreciation of its importance, critical care has not been incorporated as an essential part of the health system.[@sakaan2022]

An infant, child, or adolescent with an illness, injury, or post-operative state that increases the risk for or results in acute physiological instability (abnormal vital signs, laboratory values, or clinical findings) falls under acute paediatric critical illness^6^\
\
Many paediatric lives can be saved with low-cost resuscitation techniques and procedures, supportive care and referral pathways available at all levels of care.
Over sixty per cent of children because of poor emergency and critical care.
SDG may not be achieved unless PECC service is available to every acutely ill child.

By providing prompt and adequate medical care to critically ill children, paediatric emergency and critical care services can contribute to a decrease in childhood death rates.

## Reasons for PECC

Children who require specialised care due to severe diseases or injuries should ideally be referred or managed at the paediatric emergency or critical care (PICU).
Any space available should and can be used to offer such services.
In that sense, any clinician can advocate for or institute measures to provide PECC.

The following are typical reasons for PICU admissions:

-   **Acute respiratory distress and failure** e.g., (acute respiratory distress syndrome (ARDS), pneumonia, severe exacerbations of asthma, or any cause are all considered respiratory distress.
-   **Shock**: hypovolemic shock, septic shock, (e.g., from severe dehydration or haemorrhage). cardiogenic shock (e.g., from myocarditis or heart failure),
-   **Trauma**: accidental and non-accidental polytrauma injuries, burns, or other causes.
-   **Neurological emergencies**: Seizures, severe brain damage, cerebral bleeding, meningitis, or encephalitis are examples.
-   **Cardiovascular**: Heart failure, myocarditis, arrhythmias, and exacerbations of congenital heart disease are examples.
-   **Sepsis**: Systemic infections caused by bacteria, viruses, or fungi that result in septic shock or sepsis.
-   **Metabolic disorders** include metabolic acidosis, severe electrolyte imbalances, diabetic ketoacidosis (DKA), and inborn metabolic abnormalities.
-   Conditions that result in the failure or dysfunction of numerous organ systems, including multiple organ failure, are called multi-organ dysfunction.
-   **Post-operative support**: Children undergoing difficult procedures, especially those requiring close cardiovascular monitoring of organ function.
-   **Haematological and oncological disorders**: coagulation issues, thrombocytopenia, or severe anaemia, side effects of cancer treatment, such as tumour lysis syndrome or neutropenia caused by chemotherapy.
-   Exposure to poisonous substances, overdosing, or poisoning are examples of **toxicological** emergencies.
-   **Endocrine**: include thyroid storm, adrenal crises, and diabetic emergencies.\
    Gastrointestinal: intussusception, typhoid ileal perforation, necrotizing enterocolitis, or extreme dehydration are examples of.
-   **Renal** **disorders:** include electrolyte abnormalities, acute kidney damage, and renal failure.
