---
title: "Cardiovascular Disorders I"
author: "Dr Samuel Blay Nguah"
---

## Anatomy

The heart is located in the mediastinum of the chest, bounded anteriorly by the sternum, posteriorly by the spine and laterally by the lungs. Externally, the right ventricle is anterior. Most of the left ventricle, left atrium and right atrium are posterior. internally the right and left atria are separated by the tricuspid and mitral valves respectively. The arterial supply of the heart is through the coronary arteries while venous drainage is through the coronary sinus. The aorta and pulmonary arteries arise from the left and right ventricles. The heart has three layers:

1.  Endocardium: Inner epithelial layer of the heart
2.  Myocardium: Muscular part of the heart
3.  Pericardium: Outer layers of the heart. Divided into the visceral and parietal pericardium.

Venous blood enters the right atrium through the inferior and superior vena cavae. It empties in atrial systole into the right ventricle through the tricuspid valve. It then moves on through the pulmonary valve in ventricular systole, to the pulmonary artery and the the lungs. Blood returning from the lungs enters the right atrium through the four pulmonary veins. In atrial systole, it moves onto the left ventricle through the mitral valve. Finally, it empties into the aorta through the aortic valve.

The heart has an inherent electrical system that automatically depolarises it. The parts are:

1.  The SinoAtrial (SA) node: This is the pacemaker of the heart and depolarises the two atria.
2.  AtrioVentricular (AV) node: Receives impulses from the SA node, delays a bit before propagating
    it further
3.  His-purkinje fibre system. Responsible for the spread of electrical impulses to the ventricles

**Heart as a pump**\
There is a difference in the pumping action of the heart in utero and after birth.

1.  Fetal

    -   Most work is done by the Right ventricle

    -   The right Ventricle is therefore relatively hypertrophic

    -   Only 15% of the cardiac output is pumped into the lungs

2.  After birth

    1.   Gradual transition to Left ventricle dominance

    2.   Gradual fall in pulmonary pressure (over 6 weeks)

    3.   The left ventricle does most of the work and becomes thicker than the right

**Syetolic and diastolic functions**

*Systole*: This is the contractiel phase of the heart, Usually starts with te atrium so it empties into the ventricles befor the ventricles subwsequanty contracts.

*Diastole*:  This is he relaxation phase where the heart relaxes and lets in blood. Also starts with the arrium and then hte ventricles. 

*Complaince*: This describes how easily the heart chamber relaxes in response to the inflow of blood. 


