---
title: "Child History & Examination"
author: Prof Sampson Antwi
date: 2025-05-17
---

## Introduction

To clerk a case is to take a comprehensive **history,** perform a thorough **physical examination**,
form an impression about the most plausible diagnosis, known as a provisional diagnosis, order
investigations that will confirm this provisional diagnosis, and then plan a **definitive
treatment** based on the confirmed diagnosis.

## The Focus of Pediatrics Clerkship

After a complete clerking of a patient, a reasonable Provisional Diagnosis must be arrived at, which
can then be confirmed with relevant investigations. The nutritional status of any child should be
determined at the end of each pediatric case clerked.

**Differential diagnosis**: In most patient clerking situations, more than one plausible
investigation may be considered after a history and physical examination. In such situations, all
the plausible diagnoses are differential diagnoses of each other.

**Different, distinctive diagnoses**: In some situations, the patient may present with more than one
unrelated disease. For example, a patient who presents with pneumonia may also have septic
arthritis. Such different and distinct diagnoses are not differentials of each other

History

History-taking is pivotal in all medical encounters, whether in emergencies or in “stable”
encounters or consultations.

Paediatric History is essentially the same as adult history, albeit with five additional segments:

1.  Informant
2.  Pregnancy, Birth & Neonatal History     
3.  Immunization History  
4.  Dietary History  
5.  Developmental History

## The 15 Elements of Pediatrics History

A full history must consist of the following 15 elements:

1.  The Informant
2.  Demographics
3.  Presenting Complaint
4.  History of Presenting Complaint (HPC)
5.  Direct Question
6.  Systemic Enquiry
7.  Past Medical History
8.  Drug History
9.  Pregnancy/Birth & Neonatal History
10. Immunization History
11. Dietary History
12. Developmental History
13. Family History
14. Social History
15. Summary

### Informant

The role and importance of an informant in paediatric history are as follows:

-   To help with the provision of history. In infants and young children, the history is essentially
    given by the informant. In older children and adolescents, the sick child could contribute to
    the history.
-   To be reasonably sure whether the history so obtained is reliable or not

The following information should be requested of the informant regarding themselves: their name,
relationship to the patient, level of education, and whether they witnessed the current illness from
its onset.

### Demographics of Patient

This should cover the patient’s name, sex, age, residential address, religion, and NHIS enrolment.
 The importance of patients’ demographics is foremost for patient identification. Additionally, the
sex & age of a patient may point to certain disease types and rule out others. For example, an
infant girl straining at micturition has a form of urethral obstruction, but it cannot be a
posterior urethral valve since PUV occurs exclusively in males.  Similarly, bronchiolitis is not a
usual consideration for a 5-year-old with cough, breathlessness, and wheeze since bronchiolitis
occurs almost always in children under 2 years old. The residential address can help identify the
diseases to which the patient is at risk. For example, a patient may be residing in an area where
certain diseases are endemic. For patients coming from a slum, the insanitary conditions and
congestion predispose them to diarrhoeal and skin diseases.

**Note:** A family’s religion may warn about potential conflicts with certain treatments, such as
blood transfusions. Having an active insurance plan ensures the affordability of care to some
extent.

### Presenting Complaint (PC) or Chief Complaint

This elicits the symptoms the patient is presenting with, together with their duration, in a
chronological manner. The importance of the presenting complaint lies in its ability to open up the
whole history to the system(s) involved in the disease process and the potential disease under
discussion. It serves as the gateway to the disease process under review, as every disease manifests
in its unique way. Identifying the system(s) involved allows asking further questions about that
system in direct questioning (ODQ).

### History of Presenting Complaint(HPC)

This provides detailed accounts of each symptom reported in the PC, presented in chronological
order. It also gives details of the characteristics of the symptoms, relieving and aggravating
factors, as well as treatments that have been sought so far. The importance of the HPC is to obtain
a complete picture of each symptom. The characteristics of the symptoms may provide clues to the
disease under review.

### On Direct Questioning (ODQ)

This is a focused questioning technique that asks for further symptoms from the system(s) implicated
by the presenting complaint, to narrow down to the likely diagnosis. Where no particular system is
identified, direct questioning is conducted to identify the likely system of infection or
inflammation. For example, if fever is the only symptom presented in the presenting complaint (PC),
direct questioning is conducted to identify the likely system of infection or inflammation. For
instance, symptoms suggestive of infection in the respiratory, gastrointestinal (GIT),
musculoskeletal, central nervous system (CNS), genitourinary, ear, nose, and throat (ENT), etc.,
should be asked to narrow down to the likely disease. If any positive symptom is elicited in the
ODQ, its duration and characteristics should be stated as well.

### Systemic Enquiry (Review of Systems)

This section examines the “unaffected systems” to determine if they are involved (through concurrent
diseases or as a result of complications from the primary disease). Here, key diagnostic symptoms
are asked in each of the systems (GIT, cardiovascular, respiratory, CNS, musculoskeletal,
genitourinary, integumentary, endocrine). Review of Systems also allows obtaining all the symptoms
the patient has (e.g., in case we did not take note of some symptoms the informant mentioned in the
PC, or the informant stopped short of all the symptoms the patient had)

### Past Medical History

This section assesses four (4) things:

-   Any medical condition the patient is known to have, current or previous, e.g., sickle cell
    disease, Asthma, Epilepsy, Tuberculosis, hypertension, diabetes, etc.
-   Previous hospital admissions, and if so, when and for what condition?
-   Previous blood transfusion
-   If the condition s/he is currently presenting with has occurred in the past. This is important
    as the recurrence of a symptom may give a clue to diagnosis. For example, recurrence of bodily
    swelling may point to relapsing nephrotic syndrome, and recurrence of afebrile seizure may point
    to epilepsy.

### Drug History

This section assesses four (4) things:

1.  Medications taken so far for this current illness (usually captured in the HPC)
2.  Whether a patient is on long-term medications. This may give a clue to an underlying medical
    condition, even if the informant failed to mention the condition in the past medical history
3.  Any [known]{.underline} drug & food allergies. If a patient has known allergies and a doctor
    fails to extract that information and goes ahead to give that forbidden medication, the
    practitioner may be liable for disciplinary actions and even prosecution should the patient
    suffer grave effects of the allergy.
4.  Any herbal medications, habitually or acutely, for this illness.  The importance is that the
    herbs may be responsible for the illness under review, since the potential toxic effects of most
    herbs have not been elucidated and documented, unlike orthodox medicine, whose side effects
    could easily be elucidated

### Pregnancy, Birth & Neonatal History

This section assesses the patient's history during their conception, delivery, and neonatal life. It
is not the pregnancy that the mother may be carrying at the time of clerking the sick child. The
importance lies in the fact that any disease a mother suffered during pregnancy could affect the
offspring of that pregnancy. The same applies to the consequences of labor and delivery, as well as
the neonatal life of that child. The following information should be sought for in the pregnancy,
labour, and neonatal life:

#### Pregnancy

When booking for antenatal care (ANC) was done, any significant diseases encountered by the mother
during that pregnancy (e.g., diabetes, hypertension, rash, febrile illness, jaundice, admissions,
and if so, for what condition) should be noted. Febrile illness, rash, and jaundice could all point
to a possible TORCH infection in the mother. Whether the pregnancy was carried to term or not should
be inquired about.

#### Birth

The gestation of that pregnancy (term or not), the mode of delivery of that child (spontaneous
vaginal, induced labor, C/S, etc.), the baby’s condition at delivery, whether the baby cried at
birth, whether the baby needed resuscitation, and how soon after birth the baby was discharged could
all indicate how well or otherwise the baby was at birth. The birth weight should also be asked for.

#### The Neonatal Life

Any neonatal illnesses. In particular,  jaundice, febrile illness, or admissions would be important
to ask.

### Immunization

 Immunization is an important tool in preventing infectious diseases in children. A child who is not
immunized is at significant risk of acquiring a severe form of infectious disease and of dying
within the first few years of life. It is essential to determine whether the child’s immunization is
up to date or completed, based on the child’s age and the national immunization schedule. This
information should be cross-checked with the immunization card, if available. The presence of a BCG
scar should be checked to ensure that at least some vaccinations have been initiated. Also, a BCG
scar failure in those immunized may lead to failure of BCG immunization in a tiny minority. If some
immunizations are detected to have been missed, the reasons for the missed immunizations should be
investigated, and if it is still within the appropriate vaccination age, the child should be
administered those immunizations.

### Dietary History

Since children are growing species that require nutrients for both growth and development, a
comprehensive dietary history is a key component of the pediatric history. Information to be sought
under this section includes: the breastfeeding history (in all cases) and a typical 24-hour dietary
history, with an emphasis on complete meals rather than just the main food type, e.g., rice with
tomato stew and fish for lunch, rather than just “rice”. The meal should be assessed for both
quality (balanced meal) and quantity. For toddlers, types of complementary foods and frequency of
feeds, including night feeds, should be sought. Fruits and Snack intake (meals taken in between main
meals) should all be assessed. Whether a child was fed breastmilk exclusively or was exposed to
cow’s milk early in life has implications for diseases in later childhood, e.g., allergic
conditions, metabolic conditions, etc, hence the importance of breastfeeding history in all cases.

### Developmental History

At any point in a child’s life, their level of development must be assessed to determine whether
they are progressing at an appropriate rate for their age.

**Four** areas of development should be assessed, namely:

1.  Gross motor development, e.g., sitting, standing, walking
2.  Fine motor development (use of hands in coordination with vision)
3.  Hearing & Speech development
4.  Social development (interactions with parents & others + bladder and bowel control/continence)

Where a developmental abnormality is detected, it is essential to review the pregnancy, birth,
neonatal history, as well as nutritional and past medical history, to identify potential insults to
the brain that may have occurred during this period.

### Family History

The family history assesses for any diseases in the family that could potentially have been
transmitted to the patient, either through heredity or environmental factors (common risk factors).
In particular, diseases such as sickle cell disease, asthma, epilepsy, tuberculosis, HIV,
hypertension, and diabetes in a parent or sibling are important to inquire about. Acute illnesses,
such as a runny nose, diarrhea, and febrile convulsions (if a child has a history of these), would
also be important to note from the family. The family tree may be assessed in the family history or
under the social history, as given below.

### Social History

The family’s social status is a significant predictor of risk factors for the child’s disease, as
well as the family's ability to manage the prescribed treatment effectively.  

Information sought for under the social history covers the following six (6) areas:

1.  **Parents**: their ages, level of education, and occupation. Whether they are in a stable
    marriage or not. If a parent has passed, the circumstances of their passing and the likely cause
    should be sought.
2.  **Siblings**: Number, ages, and sexes, as well as their current school status. If a sibling has
    passed away, the circumstances of their passing should be noted.
3.  **Residential facility**: The number of sleeping rooms, the number of people who sleep with the
    patient, the ventilation of the room (including windows), and the use of mosquito nets.
4.  **Water & Sewage**: Source of drinking water, toilet facilities, and means of waste disposal
5.  **Financial support** for the child’s upkeep
6.  **Social habits of parents** like smoking & drinking (Home environmental risk factors for
    diseases, e.g., a child heavily exposed to smoking will be at risk of respiratory diseases like
    asthma and pneumonia)

### Summary of History

The summary uses not only the symptoms elicited but also any other relevant information obtained
from any segment of the history that is worthy of note. Typically, it mentions the patient’s name,
age, presenting complaint, and all other essential information in a sentence or two.

## Physical Examination

This follows after obtaining the comprehensive history. Always begins the physical examination with
**Anthropometry**:

1.  Weight, weight-for-age SD score, its interpretation (normal, abnormal, etc)
2.  Height, height-for-age SD score, its interpretation (normal, abnormal, etc)
3.  Weight-for-height SD score (for children up to 5 years), its interpretation (normal, abnormal,
    etc)
4.  BMI (for children \> 5 years), BMI-for-age centile, its interpretation (normal, abnormal, etc)
5.  Mid-Upper-Arm-Circumference (MUAC, for 6 months to 5 years), its interpretation
6.  Head circumference percentile (for children up to 5 years) and what it means

 Of note, WHO simplifies the definitions of anthropometry as follows:

Findings outside the borders of -2SD and +2SD are abnormal, and values -2SD to +2SD are normal. If
the values are outside -3SD and +3SD, then they are severely abnormal, e.g., moderate underweight if
WFA is \< -2SD, severe underweight if WFA \<-3SD, overweight if WFA \>+2SD, and obese if WFA \>+3SD.

**Vital Signs:** Temperature, Pulse rate, volume & rhythm, Respiratory rate, Oxygen saturation
(SPO2), Blood Pressure

### General Examination

This assessment evaluates the general state of the patient, including their appearance, distress
level, position in bed, nutritional status, state of consciousness, and other relevant factors. It
then assesses for pallor, jaundice, lymph node enlargement, pedal edema, hydration status, warmth in
the hands, capillary refill, clubbing, or any other stigmata of disease. Additionally, it examines
the skin for rashes, pigmentation, and any eruptions.

### System-by-System Examination

This should cover [at least the four major systems: Cardiovascular, Respiratory,
Gastrointestinal/Abdomen, and the central nervous system]{.underline}. Note that all four systems
must be examined for every case clerked, regardless of the system affected by the disease. Other
systems to note include the musculoskeletal, genitourinary, integumentary (comprising skin and
mucous membranes), and endocrine systems.

#### Respiratory System Examination

**Inspection**: Always begin by assessing the respiratory rate and respiratory effort (quiet or
distressful). Then check for cyanosis and the shape of the chest.

**Palpation:** Palpate the chest wall for tenderness, centrality of the trachea, and lymph nodes (if
not already assessed during the general examination). Additionally, assess chest expansion (for
older children only) and tactile fremitus (for older children only).

**Percussion:** The percussion fingers should always be placed horizontally along the intercostal
spaces and NEVER across the ribs or scapulae. All chest zones, anteriorly, posteriorly, and
laterally, should be percussed. It is more convenient to finish the anterior and lateral chest
examination before moving to the back. 

**Auscultation:** The assessment should report on the volume of air (adequacy of air entering
lungs), nature of breath sounds, any additional sounds, and vocal fremitus

### Cardiovascular System Examination

A convenient style of cardiovascular examination is to move from the **hands** (for warmth, CRT,
clubbing, and cyanosis), wrist (for pulse), arm (for blood pressure), neck (for distended veins),
and then settle on the heart or coronary arteries. However, the patient's general position in bed
(propped up or not), use of supplementary oxygen, respiratory effort, and mouth for central cyanosis
should all be noted, if not already captured during the general examination.

### The COR/Heart

**Inspection:** Inspect for any bulge, precordial pulsations

**Palpation:** Palpate for the Apex beat, heaves, and thrills

**Auscultation:** Auscultate over all four areas for quality of the heart sounds 1 & 2, rhythm of
the heartbeat, murmurs, and any added sounds. If a murmur is detected, its characteristics must be
reported, and the point of maximal sound (which may indicate the valve affected or position of a
shunt lesion) as well as its radiation.

Typically, there is no **percussion** in COR examination!

### Gastrointestinal System Examination

A typical GIT examination is from mouth to anus, covering the abdomen (liver and intestines).

However, GIT examination may be limited to the Abdomen.

### Abdominal Examination

**Inspection:** Exposure - The abdomen should be reasonably exposed from the nipple level down to
both inguinal creases. The genitals must be covered for privacy, but must be inspected. The size of
the abdomen (using the chest wall as a reference, both anteroposteriorly and laterolaterally),
position of the umbilicus, movement with respiration, presence or absence of distended veins or
scars, and the presence of hernia orifices should be commented on. If the patient is edematous,
check for edema of the genitals.

**Palpation:** Perform light palpation to assess tenderness in all nine regions. If masses are
detected during this examination, they should be reported. Deep palpation for the Liver, Spleen,
kidneys, and any other masses felt during light palpation

**Percussion:** Percuss for fluid (use shifting dullness if the fluid is judged to be mild to
moderate, and use fluid thrill if the fluid is judged to be severe). Always percuss at the level of
the umbilicus with the fingers spread out.

If percussion note is tympanitic across the hemi-abdomen to the flank, there is no fluid. If it is
dull all through, then the abdomen may be full of fluid, in which case, fluid thrill will be
preferred to use. If there is perceived dullness at the flank but the dull note does not change to
tympanitic at the shift of the patient to the opposite site, then there is no fluid in the abdomen.

**Auscultation:** Auscultate for bowel sounds by using the diaphragm of the stethoscope around the
umbilicus. Report on the presence or absence of bowel sounds and their pitch. Bowel sound
auscultation is typically performed over 2 minutes. If no bowel sounds are heard over this period,
the bowel sounds are presumed to be absent. In some cases, bruit can also be auscultated.

### Central Nervous System Physical Examination

Here, five (5) areas should be examined and reported on, namely:

1.  **The level of Consciousness:** The Blantyre coma scale may be used (for children under 5 years)
    or the modified Glasgow coma scale.
2.  **Signs of meningeal irritation**: Check for Neck stiffness, Kernig’s sign, and Brudzinski's
    sign. Bulging fontanel may be elicited in babies, but this is often a late sign. Fever with
    irritability is a specific indicator of meningitis in this special group.
3.  **Cranial nerves examination:** Examination of the cranial nerves should be performed
4.  **Motor system:** Assess for the Tone, Power & Reflexes \[TPR\])
5.  **Sensory system:** Assess fine and deep touch, coordination, gait, and joint position sense

## Provisional Diagnosis & Differential Diagnosis

Information from history and examination is synthesized to arrive at a likely diagnosis
\[provisionally\] + all other potential diagnoses. Notably, if there are two or more separate
diagnoses, such as malaria, pneumonia, and otitis, these remain separate diagnoses and not
differential diagnoses of one another. Differential diagnoses are usually (but not always) exclusive
of one another; for example, is it pneumonia or heart failure?

## Investigations

**Main and supportive**

Always start with the main investigations that will lead to the confirmation of the diagnosis before
coming to the supportive (ancillary) tests. For example, a Chest X-ray is diagnostic for pneumonia,
while a full blood count looking for neutrophil leukocytosis is supportive.

## Definitive Diagnosis

Based on the results of investigations, a definitive diagnosis is then made.

## Treatment Plan

Based on the suspected or definitive diagnosis, a treatment plan is formulated:

**Main treatment**: The specific treatment recommended for the particular disease. For example,
antibiotics for infectious diseases

**Supportive treatment**: Those treatments that relieve symptoms. For example, analgesics for pain,
antipyretics for fever

Note on **Empiric Treatment:** At the point of provisional diagnosis, while awaiting confirmation of
the disease through appropriate diagnostic investigations, treatment is usually initiated based on
the most likely anticipated diagnosis. Such treatment intervention is called empiric treatment. For
infectious diseases in which cultures have been taken and the results are waiting, the likely
isolate with known antibiotic susceptibility is usually initiated, which will be reviewed either for
continuation or discontinuation based on the culture and sensitivity results obtained.

**Emergency management:**

Where a case is life-threatening and requires emergency intervention, it may not be necessary to
wait and go through the details of clerking outlined above. In such emergency cases, a brief history
may be taken, and depending on the life-threatening issues identified, emergency interventions may
be instituted to stabilize the patient before proceeding with a full clinical review.

USEFUL BOOKS

[Clinical Methods by Hutchison and
Macleod](https://shop.elsevier.com/books/hutchisons-clinical-methods/glynn/978-0-7020-8265-8)
