---
title: "Malaria"
author: "Prof Daniel Ansong"
date: 2024-06-23
---

## Introduction

Malaria is an infectious disease caused by plasmodium species. Five types of species are known to
affect man. *Plasmodium falciparum*, *Plasmodium vivax*, *Plasmodium malaria*, *Plasmodium ovale*,
and *Plasmodium knowlesi*.[@poespoprodjo2023] In sub-Saharan Africa, *Plasmodium falciparum*
infection is known to be the highest cause of malaria and the most complicated form of malaria in
populations at risk of disease. The P. falciparum causes most mortality from the disease. The
geographic distribution of the species on the African continent is well
described.[@poespoprodjo2023] The World Health Organization recognises malaria as an important
disease affecting children and pregnant women in sub-Saharan Africa and among the diseases
contributing to the high under-five mortality.[@who2023worldmalaria]

## Epidemiology

**Global**: The global estimate of malaria based on 2022 data estimated over 249 million cases with
about 608,000 deaths. There was approximately a 28% reduction in cases and a 50% reduction in
mortality between 2000-2022. Ninety per cent of the cases and deaths emanate from sub-Saharan
Africa.[@who2023worldmalaria]

**Regional**: In Africa, there were 232 million cases representing about 94% of global cases and
about 580,000 deaths. Nigeria, Chad, Niger, Sudan and DRC are among the top 5 countries with the
highest disease burdens. This is attributable to poverty, weak health systems and environmental
conditions.[@who2023worldmalaria]

**Country**: In Ghana, malaria is the third leading cause of under-5 morbidities and mortality.
Pneumonia and diarrhoea account for the first and second causes of under-five morbidities. The
disease is endemic in rural, overpopulated communities and slums. The northern region of Ghana
experiences peak incidence during the rainy season.

## Presentation

**Uncomplicated malaria**: Uncomplicated malaria is associated with fever, chills, rigours,
lethargy, nausea, vomiting, poor feeding, and diarrhoea in younger children. Older children present
with headaches, myalgia, and abdominal pain. It is generally characterised by non-specific clinical
features that are well documented in the 2013 [WHO Handbook on Management of Severe
Malaria](https://factsforlife.org/pdf/management-of-severe-malaria-eng.pdf).

**Complicated malaria**: The transition between uncomplicated to complicated malaria is not
predictable. Therefore, there is a need for a high index of suspicion of complicated malaria in
managing children with malaria.[@marsh1996; @marsh1995]

::: callout-note
## Note

There is no intermediary stage called **moderate malaria**.
:::

Clinical parameters that signal the presence of complicated (severe) malaria include clinical signs
and symptoms with laboratory indicators. @tbl-gen-sev-malarai-clinical and @tbl-gen-sev-malarai-lab
outline the features suggestive of complicated malaria.

::: {#tbl-gen-sev-malarai-clinical}
+-----------------+---------------------------------------+---------------------------------------+
| SN              | Clinical Signs and Symptoms           | Comments                              |
+=================+=======================================+=======================================+
| 1               | Prostration                           | Weakness associated with the          |
|                 |                                       | inability to sit, stand, or walk. In  |
|                 |                                       | younger children, the inability to    |
|                 |                                       | suckle                                |
+-----------------+---------------------------------------+---------------------------------------+
| 2               | **Central Nervous System**            | Blantyre Coma Score of \<3 In the     |
|                 |                                       | presence of malaria parasite is       |
|                 | 1.  Convulsions (Multiple \> 2 in 24  | classified as cerebral malaria.       |
|                 |     hours)                            |                                       |
|                 | 2.  Loss of consciousness (Blantyre   |                                       |
|                 |     Coma Score \<5                    |                                       |
|                 | 3.  Abnormal motor function           |                                       |
|                 | 4.  Abnormal Cranial nerve function.  |                                       |
|                 |     Specifically Cranial 3, 4,5, 6, 9 |                                       |
|                 |     and                               |                                       |
|                 |     10.                               |                                       |
|                 | 5.  Cotton wool and haemorrhage on    |                                       |
|                 |     the retina                        |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 3               | **Haematological**                    | Obtained through history, physical    |
|                 |                                       | examination and complete blood count. |
|                 | 1.  Severe pallor (anaemia)           |                                       |
|                 | 2.  Haemoglobinuria                   |                                       |
|                 | 3.  Bleeding                          |                                       |
|                 | 4.  Jaundice                          |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 4               | **Renal**                             | Measurement of the urine and fluid    |
|                 |                                       | intake is critical to estimate        |
|                 | 1.  Oliguria                          | oliguria and anuria.                  |
|                 | 2.  Anuria                            |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 5               | **Respiratory**                       | These could signal severe pneumonia.  |
|                 |                                       | It should be radiologically           |
|                 | 1.  Respiratory Rate  \> age-specific | confirmed.                            |
|                 |     limit                             |                                       |
|                 | 2.  Oxygen saturation \< 92%          |                                       |
|                 | 3.  Pulmonary oedema                  |                                       |
|                 | 4.  Chest wall indrawing              |                                       |
|                 | 5.  Crepitation on auscultation       |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 6               | **Cardiovascular**                    | Assessment based on clinical          |
|                 |                                       | examination                           |
|                 | 1.  Reduce Capillary Refill Time.     |                                       |
|                 | 2.  Hypotension                       |                                       |
|                 | 3.  Weak Pulse                        |                                       |
|                 | 4.  Cold and clammy extremities       |                                       |
+-----------------+---------------------------------------+---------------------------------------+

: Signs and symptoms suggestive of complicated malaria
:::

::: {#tbl-gen-sev-malarai-lab}
+-----------------+---------------------------------------+---------------------------------------+
| SN              | Laboratory parameter                  | Comments                              |
+=================+=======================================+=======================================+
| 1               | **Central Nervous System**            | Rule out other causes of              |
|                 |                                       | encephalopathy, i.e. Meningitis,      |
|                 | Coma Score of \<3 In the presence of  | encephalitis, hypoglycaemia, hepatic  |
|                 | malaria parasite is classified as     | and failure.                          |
|                 | cerebral malaria.                     |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 2               | **Haematological**                    | Bedside point-of-care devices and a   |
|                 |                                       | complete blood count are required.    |
|                 | 1.  Severe Anaemia Hb \<5g/dL or PCV  |                                       |
|                 |     \<15%                             |                                       |
|                 | 2.  Plasma Bilirubin \>50 umol/L      |                                       |
|                 |     (3mg/dL)                          |                                       |
|                 | 3.  Bleeding  (thrombocytopenia)      |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 3               | **Renal**                             | Blood chemistries are required to     |
|                 |                                       | establish renal complications.        |
|                 | 1.  Plasma creatinine  \>265umol/L    |                                       |
|                 |     (3mg/dL)                          |                                       |
|                 | 2.  Blood urea \> 20 mmol/L           |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 4               | **Respiratory**                       | Could signal severe pneumonia         |
|                 |                                       |                                       |
|                 | 1.  Respiratory Rate                  |                                       |
|                 | 2.  Oxygen saturation \< 92%          |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 5               | **Cardiovascular**                    | Basic bedside clinical examinations   |
|                 |                                       |                                       |
|                 | 1.  Reduce Capillary Refill Time.     |                                       |
|                 | 2.  Reduce blood pressure             |                                       |
|                 | 3.  Weak Pulse                        |                                       |
|                 | 4.  Cold and clammy extremities       |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 6               | **Metabolic**                         | Clinically, it will manifest as       |
|                 |                                       | Kussmaul breathing (deep, rapid       |
|                 | 1.  Base deficit of \> 8mEq/L         | breathing)                            |
|                 | 2.  Plasma Bicarbonate  of \<15mmol/L |                                       |
|                 | 3.  Lactate of \< 5mmol/L             |                                       |
|                 | 4.  Hypoglycaemia  \<2.2 mmol/L       |                                       |
+-----------------+---------------------------------------+---------------------------------------+
| 7               | Hyperparasitaemia:                    | Microscopy in resource endowed        |
|                 |                                       | institution                           |
|                 | > \>2%/100 000/µL in low-intensity    |                                       |
|                 | > transmission areas or \>5% or       |                                       |
|                 | > 250 000/µL in areas of high stable  |                                       |
|                 | > malaria transmission intensity      |                                       |
+-----------------+---------------------------------------+---------------------------------------+

: Laboratory features suggestive of complicated malaria
:::

## Risk factors

There are genetic factors that protect against the development of malaria. The genetic factor and
the mechanism proposed to lead to the protection against malaria are shown in Table 1 of the
publication titled [Genetic polymorphisms linked to susceptibility to
malaria](https://malariajournal.biomedcentral.com/articles/10.1186/1475-2875-10-271#citeas) by
@driss2011a. In sub-Saharan Africa, sickle cell anaemia and glucose-6-phosphate dehydrogenase
deficiency are the most common genetic disorders.[@carter2011; @moeti2023]

## **Management**

**Uncomplicated malaria:** The WHO recommends Artemisinin-based Combination Therapy (ACT) to manage
uncomplicated malaria. Mono-therapy is NOT recommended in patients living in endemic and
high-transmission settings. Treatment should be swift; therefore, home management of malaria is
highly recommended.

**Complicated malaria:** The aim of managing severe malaria is to prevent death and complications.
Severe malaria can result in death within hours of progression from uncomplicated malaria to
complicated. Prompt and swift response to clinical changes is paramount.

The WHO recommends parenteral artesunate and appropriate support care based on the clinical
progression. Complicated malaria is a multi-system disease; therefore, clinicians should prioritise
their care, emphasising supportive care. It is a medical emergency. Healthcare professionals should
identify life-threatening situations like hypoglycaemia and hypoxaemia secondary to heart failure
from complications such as severe anaemia and pulmonary oedema, convulsion and other central nervous
manifestations from brain oedema and potentially raised intracranial pressure. Children can develop
compensated and decompensated shock. When present, it should be corrected and monitored until the
patient is stable.

Full doses of parenteral artemisinin (artesunate or artemether) should be provided, followed by
complete doses of ACT. Rectal Artesunate is recommended in situations where parenteral artemisinin
is not available.

**Parenteral artesunate:** IV artesunate should be given immediately after malaria is confirmed at 
2·4mg/kg per dose at 0, 12, and 24 hours, then every 24 hours till the child is stable and able to
tolerate oral ACT.

::: callout-note
## Note

Children with body weight \<20 kg should receive 3·0 mg/kg per dose to ensure equivalent exposure to
the drug.
:::

Other alternate medications are:

-   Intramuscular artemether: initial dose 3·2 mg/kg, then 1·6 mg/kg every 24 h

-   Intravenous quinine diluted in 5% dextrose: loading dose of 20 mg/kg infused over 4 hours, then
    10 mg/kg every 8 hours infused no faster than 5 mg/kg per hour.

    ::: callout-note
    ## Note

    Quinine is currently not recommended, and patients on Quinine are at risk of hypoglycaemia.
    :::

-   Pre-referral rectal artesunate: Recommended in primary health-care settings in which parenteral
    drug administration is not possible104

-   Children who are stable and can take oral medication should be given a full course of oral
    antimalarial treatment as per guidelines for uncomplicated malaria.

::: callout-caution
## Caution!

Due to the risk of post-complicated malaria neurological syndrome. Mefloquine-containing
artemisinin-based combination therapies (ACT) should be avoided.
:::

::: {#tbl-gen-antimalarials}
+-----------------------+-----------------------+-----------------------+-----------------------+
| SN                    | ACT                   | Dosage                | Comments              |
+=======================+=======================+=======================+=======================+
| 1                     | Artemether–           | 0·83–4∙00 mg/kg       | Take twice a day for  |
|                       | lumefantrine          | artemether and        | 3 days with fatty     |
|                       |                       | 4·83–24∙00 mg/kg of   | food; the first two   |
|                       |                       | lumefantrine          | doses should be given |
|                       |                       |                       | 8 hours apart.        |
+-----------------------+-----------------------+-----------------------+-----------------------+
| 2                     | Artesunate–mefloquine | 4 mg/kg per day       | Taken once a day for  |
|                       |                       | artesunate (range     | 3 days                |
|                       |                       | 2–10 mg/kg) and 8·3   |                       |
|                       |                       | mg/kg per day         |                       |
|                       |                       | mefloquine (7–11      |                       |
|                       |                       | mg/kg)                |                       |
+-----------------------+-----------------------+-----------------------+-----------------------+
| 3                     | Dihydroartemisinin    | 4mg/kg per day        | Taken once a day for  |
|                       | –piperaquine          | dihydroartemisinin    | 3 days                |
|                       |                       | (range 2–10 mg/kg)    |                       |
|                       |                       | and 18 mg/kg per day  |                       |
|                       |                       | piperaquine (16–27    |                       |
|                       |                       | mg/kg)                |                       |
+-----------------------+-----------------------+-----------------------+-----------------------+
| 4                     | Artesunate            | 4 mg/kg per day of    |                       |
|                       | –amodiaquine          | artesunate (range     |                       |
|                       |                       | 2–10 mg/kg) and 10    |                       |
|                       |                       | mg/kg per day         |                       |
|                       |                       | amodiaquine (7·5–15   |                       |
|                       |                       | mg/kg) once a day for |                       |
|                       |                       | 3 days                |                       |
+-----------------------+-----------------------+-----------------------+-----------------------+
| 5                     | Artesunate–sulf       | 4 mg/kg per day of    |                       |
|                       | adoxine-pyrimethamine | artesunate (range     |                       |
|                       |                       | 2–10 mg/kg) given     |                       |
|                       |                       | once a day for 3 days |                       |
|                       |                       | and a single          |                       |
|                       |                       | administration of at  |                       |
|                       |                       | least 25 mg/kg        |                       |
|                       |                       | sulfadoxine (25–70    |                       |
|                       |                       | mg/kg) and 1·25 mg/kg |                       |
|                       |                       | pyrimethamine         |                       |
|                       |                       | (1·25–3·5 mg/kg)      |                       |
|                       |                       | given as a single     |                       |
|                       |                       | dose on day 1         |                       |
+-----------------------+-----------------------+-----------------------+-----------------------+

: Drugs recommended for the management of Uncomplicated malaria
:::

## **Monitoring of progress**

The following clinical indices fluctuate, and their serial monitoring is crucial to avoid
complications:

1.  Hypoglycaemia
2.  Shock
3.  Raise Intracranial Pressure
4.  Severe Anaemia
5.  Haemoglobinuria 
6.  Acute Kidney Injury
7.  Pulmonary Edema

## **Prevention**

**Behavioural change** to avoid the bite of infected female *anopheles* mosquitoes is important in
preventing malaria. Several modes of behavioural techniques are known. Notable is the use of
insecticide-treated bed net.

**Indoor and Outdoor spraying residual spraying** at household levels and in mass campaigns in wide
geographic areas are known to reduce malaria transmission.

**Seasonal Malaria Chemoprophylaxis** is the intermittent administration of a curative dose of
antimalaria medicine during the malaria season, regardless of whether the child is infected. This is
recommended for children living within areas with high transmission.

**Perennial malaria  chemoprophylaxis  (PMC),** also known as Intermittent Preventive treatment in
infants (IPTi)

**Vaccines:**  Two malaria vaccines are currently pre-qualified by WHO. RTS, S/Vaccines and
R21/Vaccine  RTS,S/AS01 and R21/Matrix-M vaccines are recommended by WHO to prevent malaria in
children.  Four doses for children 5 months will benefit from the vaccines. Both RTS.S and
R21/Matrix malaria vaccines are safe and efficacious, and both have been prequalified by
WHO.[@WHO_MalariaVaccines]

Eight African countries are planning to roll out malaria vaccines as part of routine childhood
vaccinations, It is expected that more lives will be saved with the introduction of the vaccine in
sub-Saharan Africa.[@WHO_MalariaVaccines]

## **Differential Diagnosis**

The following differential diagnosis should be considered in children presenting with clinical
features suggestive of malaria but with microscopy-negative slide and RDT-negative. History and
physical examination supported with appropriate laboratory investigation should lead to other
differential diagnoses shown below in @tbl-malaria-differentials.

::: {#tbl-malaria-differentials}
+--------------------------------+--------------------------------+--------------------------------+
| SN                             | Region                         | Differential                   |
+================================+================================+================================+
| 1                              | Head and Neck                  | [Bacterial                     |
|                                |                                | M                              |
|                                |                                | eningitis](id-meningitis.qmd), |
|                                |                                | Viral Encephalitis, Otitis     |
|                                |                                | Media, Tonsilitis and          |
|                                |                                | Pharyngitis Epiglottitis       |
+--------------------------------+--------------------------------+--------------------------------+
| 2                              | Thorax                         | Pneumonia, Bronchiolitis,      |
|                                |                                | Pericarditis, Carditis and     |
|                                |                                | Endocarditis                   |
+--------------------------------+--------------------------------+--------------------------------+
| 3                              | Gastrointestinal               | [Typhoid                       |
|                                |                                | fever](id-enteric-fever),      |
|                                |                                | Appendicitis, Hepatitis and    |
|                                |                                | Cholecystitis                  |
+--------------------------------+--------------------------------+--------------------------------+
| 4                              | Genitourinary                  | Cystitis and Pyelonephritis    |
+--------------------------------+--------------------------------+--------------------------------+

: Possible differential diagnosis based on history and Anatomical location
:::

## **Case Discussion**

These reviews present four hypothetical case scenarios of severe malaria in children. It illustrates
four key common pathways along which over 239,000 children die from malaria annually, either at
rural health posts or in higher tertiary institutions across sub-Saharan Africa.

**Case 1: Malaria with Haemoglobinuria**

A 4-year-old girl was seen at a Community Health Provider Services (CHPS) compound with fever,
vomiting and poor feeding. Clinical Care received at the CHPS compound included oral anti-malaria,
antipyretic and haematinic drugs. The child’s condition worsened in the subsequent 24 hours with the
passage of coca-cola-like urine, which the mother had noticed during the onset of the disease but
not to the health worker at the CHPS.  The mother reported again to the CHPS compound the next day
with the complaint of prostration and persistent fever. The child was subsequently referred to the
primary health centre and, based on Integrated Management of Childhood Illness (IMCI) criteria of
classification of severe disease, the child was finally referred to the tertiary hospital as a case
of severe malaria. The child convulsed on the way to the hospital and, upon arrival, was still
having focal seizures. Blood glucose on admission was 1.2mmol/L, haemoglobin was 3.2g/dL, and
lactate was 12.0mmol/L. Physical examination revealed a child in respiratory distress with deep
breathing. The respiratory rate was 50 cycles per minute, and the heart rate was 146 beats per
minute with weak volume. Chest auscultation revealed adequate air entry and clear lung fields.
Extremities were cold with a capillary refill time of more than 4 sec.  Hypoglycaemia was
immediately corrected with 10% dextrose, the shock was corrected with intravenous saline, and focal
seizures were controlled with diazepam per rectum.  The Blantyre Coma Score subsequently improved
from 0/5 to 2/5. The child was subsequently managed as cerebral malaria with severe anaemia
secondary to haemoglobinuria, lactic acidosis, and shock. The child was noted to have scanty urine
output (less than 0.3ml/kg/hour) on day 3 of admission.  BUN and creatinine were raised with normal
serum electrolytes. Acute renal failure secondary to malaria with haemoglobinuria was diagnosed and
managed accordingly with IV fluids and frusemide. The child had two episodes of blood transfusion
during admission. She received quinine for seven days, and by day 5, she had regained consciousness
and was walking by day 7. The child did not undergo dialysis but had complete recovery of renal
function by day 14 of admission and was discharged home on day 15. She has remained well in
subsequent reviews.

**Case 2: Malaria with Lactic Acidosis and Pulmonary Oedema**

A 4-year-old boy was referred to the paediatric emergency unit with a clinical diagnosis of severe
malaria. He presented with prostration and deep breathing. The Chest X-ray showed pulmonary oedema.

The patient had earlier been seen at a health centre with a 2-day history of fever and vomiting, for
which he received anti-malarial drugs (type unknown). The child’s condition did not improve as he
continuously vomited the medications and was feeding poorly the following day. The mother noticed
that the child’s condition had worsened with increasing breathlessness and inability to sit without
support. The mother reported to the health post, and the child was immediately referred to the
tertiary hospital.

The child arrived prostrated with acidotic deep breathing and had a respiratory rate of 66 cycles
per minute. Air entry was adequate bilaterally, with crackles at the lung bases. Her heart rate was
148 beats/minute with normal heart sounds. There was no gallop rhythm. The child had no hepatomegaly
but a splenomegaly of 6cm below the sub-coastal margin in the mid-clavicular line. The child was
conscious with a Blantyre coma score of 5/5 but prostrated (unable to stand or sit without support).
There were no other neurological deficits. Blood film comments revealed malaria parasitaemia (P.
falciparum), haemoglobin was 5.2g/dl, lactic acid was 13.3mmol/L, and normal blood glucose was
4.7mmol/L. The child was subsequently managed as a case of severe malaria with lactic acidosis and
pulmonary oedema (Acute Respiratory Distress Syndrome, ARDS). The child was managed according to the
WHO guidelines for the management of complicated malaria with IM quinine.

**Case 3: Cerebral Malaria with Raised Intracranial Pressure**

A 3-year-old boy developed a febrile illness in a rural community.  Mother gave acetaminophen at
home with temporary relief of the fever. After 12 hours, the fever recurred with vomiting. A single
episode of convulsion followed this. The child was sent to the health centre, where he was found to
have gained consciousness and had no neurological deficit. The patient was managed as malaria with
convulsion on oral anti-malaria drugs and sent home. When the parents got home, the child had
another episode of convulsion, and the child was sent back to the health centre. The child was
subsequently referred to the children’s emergency unit. The child arrived in the hospital with
ongoing generalised tonic-clonic seizures. Random blood sugar was 1.2mmol/L, for which 5ml/kg of 10%
dextrose was given immediately, and a maintenance glucose infusion was set up. Rectal diazepam was
given to abort the seizures. Further examination revealed a deeply comatose child with a Blantyre
Coma score of 0/5.  Oxygen saturation was 91%. The child had warm extremities, capillary refill time
was less than 2 sec, and was clinically pale, not cyanosed and well hydrated. The respiratory rate
was 62 cycles per minute, with occasional abnormal rhythm and effort.  The chest was clinically
clear. Heart rate was 140 beats per minute with normal heart sounds. There was no
hepato-splenomegaly. The child had increased tone, decorticate posture, increased reflexes and
extensor plantar response. The pupil size was 1mm bilaterally and was non-responsive to light. The
child was diagnosed to have cerebral malaria complicated by raised intracranial pressures. The
patient was managed according to the WHO guideline for cerebral malaria, and the department
treatment protocol-parenteral quinine was used.

**Case 4: Severe malaria with hyper-parasitemia and anaemia**

A 3-year-old child was referred to a tertiary hospital with a diagnosis of severe malaria with
moderate anaemia. Examination findings revealed a child who was prostrated with normal blood glucose
of 4.2 mmol/L, Haemoglobin of 6.5g/dl, and malaria parasite density of 679,234/uL.  The child was
managed as severe malaria with moderate anaemia based on WHO guidelines and department protocol. A
treatment course of parenteral quinine was given. After 22 hours, the child’s condition had worsened
with an increase in respiratory rate from 42 cycles per minute to 66 cycles per minute. The child
looked more prostrated with a Blantyre coma score of 2/5  (initial score of 4/5). The chest was
clinically clear; the heart rate had increased from 126 to 160 beats per minute. Hepatomegaly had
increased from 3cm to 6cm below the sub-cost margin in the mid-clavicular line. A repeat laboratory
investigation revealed a haemoglobin drop to 4.5g/dL. The child was given packed red blood cells
(20mL/kg BW) and further managed for malaria. The child responded to the treatment.

**Discussions:**

**Introduction**

The over 480,000 deaths from malaria recorded annually worldwide[@poespoprodjo2023] likely result
from one of these case scenarios. One critical question researchers and clinicians should ask is:
How can cases of malaria best be managed so that potentially complicated cases are identified early
and appropriate measures are taken to avert death?

Too many complicated malaria cases are seen across sub-Saharan Africa[@who2023worldmalaria;
@marsh1996].  As we advance in the knowledge of malaria pathogenesis and chemotherapy, we have to
translate the research knowledge into good clinical practice and standard treatment. The case
fatality rate from complicated malaria varies across Africa.[@who2023worldmalaria] Competencies of
health personnel in assessing children, among others, are important factors.  The bedside provides a
good opportunity for health practitioners to pick up clinical clues that signal impending
complications; if these clues are seen at the right time, appropriate management can be instituted
early to avoid death. How can these clues be picked up to avoid these deaths in our health
institutions across Africa? The WHO Handbook on Hospital Care for Children provides guidelines for
assessing critically ill children.[@carter2011] This document should serve as training material and
medical companion for lower-level health practitioners. Appropriate use of these materials at the
lower level with the correct application of the IMCI modules should significantly impact the drive
to reduce death from malaria.[@demendonça2012]

**Review of cases**

**Case 1:** In this case scenario, a history of the passage of dark-coloured urine was enough to
suspect haemolysis in this child. If this essential symptom had been picked at the child’s first
appearance at the CHPS, it should have led to an immediate referral to a higher health centre. 

The passage of dark-coloured urine (haemoglobinuria) is a recognised complication of severe
malaria.[@crawley2004; @crawley2010] Any child who presents with such symptoms is at risk of two
potentially fatal complications: severe anaemia and acute renal failure from pigment nephropathy.
Such cases should be referred to a centre where facilities for safe blood transfusion exist. Acute
renal failure from haemoglobinuria usually responds to fluid therapy (approx 1.5 times maintenance
fluid, oral or intravenous). Haemoglobinuria is recognised as an important cause of acute renal
failure in children.[@WHO_MalariaVaccines] The case under discussion presented haemoglobinuria
followed by the two complications of severe anaemia and acute renal failure. The swift institution
of haemotransfusion therapy averted death. Her renal failure responded to conservative treatment
with IV fluid and frusemide with careful monitoring of the lung bases for any evidence of pulmonary
congestion.  It is important to note that primary-level health facilities across Africa will not be
privileged to have facilities to measure the haemoglobin levels of children reporting severe
malaria. However, a simple examination of the conjunctiva, palms and soles by these first-level
healthcare workers can detect significant anaemia in children. Similarly, enquiry about urine colour
or macroscopic inspection of a urine sample could indicate haemolysis that requires prompt review or
referral. The scientific knowledge about the pathogenesis of malaria-induced anaemia is widely
known, and the bedside clinical recognition of severe anaemia that is critical to warrant
transfusion is clear.[@WHO_MalariaVaccines] The current challenge in most sub-Saharan African
countries is recognising potentially complicated malaria cases before the complications manifest
themselves. Healthcare professionals across sub-Saharan Africa should continuously train and develop
their skills in identifying the early signs and symptoms of severe malaria.

**Case 2:** Prostration is a common presentation in children with severe malaria and an important
triage finding that health workers should not miss in both the peripheral centres and the tertiary
health institutions. It is one clue that does not rely on any laboratory or specialised care to
detect. Recognising prostration does not require extraordinary skills. Prostration is clearly
defined as a criterion for severe and complicated malaria; missing prostration could lead to an
underestimation of the disease condition and a serious delay in treatment. In the case under
discussion, the prostration was correctly recognised by the healthcare worker at the periphery,
which prompted the referral.  Clinicians in sub-Saharan Africa should develop the skill and the
consciousness to evaluate every child for prostration at the first point of contact. Prostration in
younger children who are yet to sit can be difficult to assess. The inability to suckle or drink
should raise suspicion.

Early diagnosis of pulmonary complications is key to survival. A higher respiratory rate, lower
chest wall in-drawing and recessions may be key findings in recognising pulmonary complications.
Counting respiratory rates accurately over one minute and relating them to other clinical signs and
symptoms is the simplest way of determining children who are critically ill from malaria with
possible pulmonary complications.

**Case 3:** This patient would have died from Hypoglycaemia, Respiratory Arrest secondary to raised
intracranial pressure or other complications of cerebral malaria. In low-level health settings
across sub-Saharan Africa, glucose measurement is not routinely done. However, a history of poor
feeding and or vomiting in the presence of prostration and unconsciousness should prompt health
workers about the possibility of hypoglycaemia. Hypoglycaemia secondary to malaria is known to be
associated with very high mortality.[@who2023worldmalaria] Management of the condition is simple and
cheap.  In advanced cases of severe malaria where there has been the involvement of the brain,
raised intracranial pressures ensue. Failure to recognise this life-threatening complication
eventually leads to respiration arrest and eventual death. Early clues known from scientific
knowledge should be applied at the bedside. Abnormal respiratory patterns, deep breathing without
blood gases and electrolytes, abnormal postures, and pupillary changes are the bedside clinical
signs of potential raised intracranial pressure.

**Case 4:**  Early clinical signs in a child with severe malaria and hyperparasitaemia can be
misleading, especially if health staff do not have much experience in monitoring the clinical signs
of deterioration.  The progression of clinical disease and the care available determine whether the
child would survive severe malaria. In the presence of heavy parasitaemia, health practitioners
should be aware that even moderate anaemia could rapidly lead to severe anaemia, which could
subsequently lead to heart failure. All parasitised red cells will eventually haemolyse in the
spleen and other reticuloendothelial systems. In addition, because of the rosette formation, all the
red cells pulled into the spleen will be haemolysed. Children with acute malaria, therefore, rapidly
develop severe anaemia, and clinical teams should have a high index of suspicion as well as prepare
to administer blood transfusion whenever the need arises.  The majority of the over one million
malarial deaths that occur annually do occur because of the complications associated with the
disease. Prompt recognition of these complications at all levels of health care and well-established
referral systems will go a long way in reducing these deaths. No death was recorded among these four
cases that presented multiple complications associated with severe malaria. Sub-Saharan Africa's
challenge is translating the numerous research findings conducted in Africa into good clinical
practice. 

**Overall Comment:**

Basic clinical indices that are well known to signify impending complication or life-threatening
malaria should be applied in triaging and reassessing all children who present with malaria. From
the health centre to the tertiary hospital, these clinical indices can guide health officials in
managing children according to standard protocols and guidelines, thus avoiding death from
complicated malaria.
