---
title: Hypertension
author: "Prof (Med) Sampson Antwi"
---

## Outline

-   Definition of hypertension in children
-   Methods for measuring blood pressure
-   Clinical conditions in which blood pressure measurements become imperative in children
-   Step-by-step evaluation of a child with hypertension
-   Commonly used anti-hypertensives in children
-   Hypertensive encephalopathy

## The Concept of Blood Pressure

Blood pressure is the force exerted by the blood against any unit area of the vessel wall. That is:
$$P=F/A$$

Physiologically, $$BP = CO \times TPR$$ and $$BP = Stroke Volume \times HR \times TPR$$ Where:

-   $HR$ is the Heart Rate
-   $BP$ is the Blood Pressure
-   $HR$ is the Total Peripheral Resistance
-   $CO$ is the Cardiac Output

## Ways of measuring blood pressure

1.  **Direct intra-arterial** measurements by placing a catheter into the vessel and measuring the
    pressure "in line" with the vessel (end-on-pressure). This method is used by physiologists and
    Intensivists. The principle is employed in the measurements of central venous pressure &
    intracranial pressure in clinical practice.
2.  **Auscultatory method** with the use of a sphygmomanometer (either mercury or aneroid) and a
    stethoscope. This is the gold standard in clinical practice. K1 & K5 sounds are measured for
    systolic & diastolic pressures respectively. Values obtained are generally lower than direct &
    oscillometric measurements.
3.  **Palpation method** (flush technique) with the use of a sphygmomanometer and palpating finger.
    Largely unreliable. Only systolic blood pressure can be measured with this technique. The
    palpated pulse is generally lower than K1 by 10mmHg.
4.  **The oscillometric method** uses a sphygmomanometer and a monitor e.g. digital blood pressure
    devices & data map. Here, pulsatile blood flow through arterial wall oscillations is transmitted
    to the cuff encircling the extremity. K1 is recorded at the point of rapid increase in
    oscillation amplitude. K5 is recorded as the point of a sudden decrease in oscillation
    amplitude. Values obtained by oscillometric measurements are generally higher than auscultatory.
5.  **Doppler ultrasound technique**: Here a Doppler ultrasound is held over the pulse to magnify
    the sound so that it is audible without a stethoscope. The sound detected may be 5mmHg higher
    than K1.
6.  **Ambulatory blood pressure measurements**. Here, multiple measurements are recorded over time
    (e.g. 24 hours) with digital devices attached to the limb whilst the patient engages in normal
    activities outside the hospital. Results are analysed on a computer or paper tracer built into
    the device using the mean of the readings. It provides a truer picture of blood pressure trends
    Useful in diagnosing "white coat hypertension" and nocturnal hypertension (absence of a normal
    physiological drop in blood pressure during sleep).

## Definition of Hypertension in children

1.  **In adults**: epidemiological definition based on the risk of adverse events (e.g. Stroke) is
    \>140/90mmHg
2.  **In children**: Hypertension is defined statistically based on normative data: ≥ 95th centile
    for age, height, and gender (Refer to height centile chart and blood pressure levels). By this
    statistical definition, 5% of children will be classified as hypertensives.

## Other Definitions

-   **Normal blood pressure**: \< 90th centile for age, height, and sex
-   **Pre-Hypertension**: 90th -- \<95th centile for age, height, and sex
-   **Stage 1 Hypertension**: 95th - 99th + 5 mmHg
-   **Stage 2 Hypertension**: *\> 99th centile + 5mmHg*

## Sample blood pressure centile chart

[![Blood Pressure Centile
Chart](bpchart.jpg){fig-align="center"}](https://www.bing.com/ck/a?!&&p=03173e8901eee155JmltdHM9MTcwODkwNTYwMCZpZ3VpZD0xMTM3ZDFjZC1mMmJmLTY1YzctMjQ4My1jMmI3ZjNkODY0NjUmaW5zaWQ9NTE5NA&ptn=3&ver=2&hsh=3&fclid=1137d1cd-f2bf-65c7-2483-c2b7f3d86465&psq=blood+pressure+pediatric+centile+charts+pdf&u=a1aHR0cHM6Ly93d3cubmhsYmkubmloLmdvdi9maWxlcy9kb2NzL2d1aWRlbGluZXMvY2hpbGRfdGJsLnBkZg&ntb=1)

## Plotting the blood pressure centile

1.  Measure the child's height
2.  Determine the height centile. If the height centile falls between 2 centiles, use the closest
    centile. Otherwise, use the lower height centile.
3.  Determine the blood pressure centile.
4.  Classify blood pressure using the definitions above.

## Hypertensive emergency

This is an acutely elevated blood pressure with evidence of threatening end-organ damage involving
the following organs:

-   Brain (severe headache, visual changes, cranial nerve palsy, papilloedema)
-   Heart (acute chest pain & tigHypertensioness, shortness of breath)
-   Kidney (decreased urine output acutely, proteinuria & haematuria on dipstick)

It is thus a symptomatic, severe Hypertension.

## Hypertensive Urgency

This is severe hypertension without evidence of end-organ damage or symptoms. The blood pressure
should nevertheless be treated urgently but not aggressively like in a hypertensive emergency to
prevent progression into a hypertensive emergency. If possible, the patient should be managed as
in-patient

## Rules of blood pressure measurement

1.  Select the right cuff size
    -   The length of the inflation bladder should be at least 80% of the mid-arm circumference.
    -   The width of the inflation bladder is at least 40th of the mid-arm circumference.
2.  The child should rest for at least 5 minutes in a comfortable environment and position.
3.  Arm resting & supported at heart level (The reference level. Values outside this reference level
    are higher). The lower edge of the cuff is 2cm above the cubital fossa.
4.  Bladder tubings should lie over the brachial artery.
5.  Bell of the stethoscope is used
6.  K1 and k5 are used for systolic & diastolic respectively.
7.  Multiple measurements are made (preferably at different settings) and the lowest reading is
    taken. For research purposes, 3 measurements are taken and an average of the last 2 used.

Blood pressure readings obtained in the legs are 10-20mmHg higher than the arm pressure in any
individual. Arm blood pressure higher than leg blood pressure occurs in aortic coarctation distal to
ductus arteriosus.

## When to suspect hypertension

Suspect Hypertension in any child with any of the following conditions:

-   Alteration in consciousness including aggressive behavior and convulsion
-   Oedematous
-   Known kidney disease or evidence of abnormal urinalysis
-   Heart failure
-   Obesity
-   Failure to thrive
-   Stroke or other palsies including cranial nerve palsy
-   History of Low Birth Weight (small number of nephrons)
-   Unexplained anaemia, or blurred vision
-   Neurofibromatosis
-   Other syndromes like Turner & Williams

## Aetiology of hypertension

Generally, childhood Hypertension is considered to be of secondary cause until proven otherwise.
This is particularly so among the very young and the severely hypertensive. The majority (\~80%) are
of renal origin. However, the number of children with essential Hypertension is on the rise,
particularly among obese adolescents and those with a positive family history.

Broadly, aetiology can be categorized into:

-   Renal disease
-   Vascular disorders
-   Endocrine causes
-   Neurologic causes
-   Renal tumours
-   Catecholamine-secreting tumours
-   Drug-induced
-   Miscellaneous causes

However, since these are often age-specific categorizations are done by age as below:

### Neonate to One-year

**Congenital**

-   Cong lesions of the vasculature
    -   Renal Artery Stenosis
    -   aortic coarctation
-   Cong lesions of renal parenchyma
    -   Polycystic Kidney disease
    -   Dysplastic kidneys
    -   Obstructive uropathy
-   Congenital Adrenal Hyperplasia
    -   11-β hydroxylase deficiency
    -   17-αhydroxylase def

**Acquired**

-   Renal artery/vein thrombosis 20 umbilical a/v catheterisation
-   Bronchopulmonary dysplasia
-   Medications
    -   Theophylline/caffeine
    -   Phenylephrine and Ephedrine Nasal Drops in cold medications
    -   Steroids
    -   Vitamin D intoxication
-   Total Parental Nutrition (high Ca2+)
-   Maternal drug use: Cocaine/heroin

### One- to Five-year

-   Renal Artery Stenosis (RAS)
-   Glomerulonephritis
-   Renal vein thrombosis
-   Wilms tumour
-   Neuroblastoma
-   Phaeochromocytoma
-   Cystic kidney disease
-   Monogenic Hypertension (e.g. Liddle's syndrome)

### Five- to Ten-years

-   Glomerulonephritis
-   Renal scars from reflux nephropathies/Urinary Tract Infections
-   Renal Artery Stenosis
-   Cystic renal disease
-   Endocrine tumours
-   Essential Hypertension
-   Obesity

### Ten- to Twenty-years

-   Obesity
-   Essential hypertension
-   Reflux nephropathies with repeated Urinar Tract Infections
-   Glomerulonephritis
-   Renal Artery Stenosis
-   Endocrine tumours
-   Hyperthyroidism
-   Drugs (Oral Contraceptive Pill, illicit drugs)

## Clinical Evaluation of the Hypertensive Child

-   Patient's history
-   Symptoms of renal disease (haematuria, oliguria, evidence of bodily swelling, polyuria,
    enuresis)
-   Symptoms of vasculitis/rheumatology ( Joint swelling & rash)
-   PMHx (umbilical artery/vein catheterisation, previous renal disease e.g. Previous swelling)
-   Drug History (steroids, OCP, amphetamines, other illicit drugs)
-   Birth History: LBW
-   Family History of Hypertension

Clues on physical examination include:

-   Coarctation of the Aorta & Takayasu:
    -   Femoral artery delay or imperceptible
    -   Blood pressure discrepancy between arm & leg →COA, Takayasu arteritis
-   Neurofibromatosis
    -   Cafѐ au lait spots
-   RAS, Takayasu arteritis
    -   Abdominal bruit →
-   CAH
    -   Ambiguous genitalia
-   Dysmorphism suggestive of Turner or William syndromes
-   Signs of CRF: growth failure (stunted), renal rickets, anaemia, oedema
-   Bedside urine dipstick positive for protein & blood ± edoedemalomerulonephritis

## Investigations

The rationale is 2-fold:

1.  To define aetiology
2.  To assess the presence of end-organ damage

Some of the investigations include:

-   Full blood count
-   Urine dipstick, microscopy and culture
-   BUE, Serum Creatinine, Ca, Mg, PO4, blood gases
-   Uric acid
-   KUB ultrasound and Doppler studies to rule out Renal Artery Stenosis
-   Chest X-ray for cardiomegaly
-   Echocardiogram for Left Ventricular Hypertrophy (end organ damage)
-   Fundoscopy
-   Plasma Renin Activity (PRA) for RAS & renin secreting tumours
-   Pre/post captopril nuclear scan
-   MRA or CT Angiogram
-   DMSA scan for renal scars
-   Urine HVA & VMA for catechol amine secreting tumours/MIBG scintigraphy

## Uric Acid and hypertension

Uric acid is increasingly being implicated in the pathogenesis of Hypertension in both adults and
children. It is believed to cause endothelial dysfunction leading to microvascular and inflammatory
injury to the kidneys. There are also reduced levels of endothelial-derived nitric oxide (NO) and
associated elevation of RAAS. Elevated uric acid levels in hypertensive individuals are associated
with adverse outcomes like stroke. Allopurinol Rx is advocated in such individuals

## Complication of Hypertension

Some complications of Hypertension are listed below:

-   Hypertensive encephalopathy
-   Left Ventricular Failure
-   Stroke
-   Subarachnoid haemorrhage
-   Secondary renal damage
-   Retinopathy

## Treatment of hypertension

### Non-drug treatment

-   Reducing salt intake
-   Weight reduction for obesity-related hypertension
-   Intake of more vegetables on a/c of K-richness

### Drug Treatment

Principles of anti-hypertensive therapy:

-   Long-acting (once-daily medication)
-   Maximise treatment dosage before adding on
-   Agents used will come from the "ABCD" group:
    -   **A**CE inhibitor and ARBs (Avoid if RAS suspected or in hypovolaemia)
    -   **B**eta-blocker
    -   **C**alcium channel blocker
    -   **D**iuretic
    -   **E**very other drug (methyl dopa, alpha-blockers, vasodilators like hydralazine

Generally, **A & B** drugs are not combined for Blood pressure control. Rather: **A + C + D** or
**B + C + D**

## Hypertensive encephalopathy

Hypertension with changes in mental status and/or seizures. Other manifestations are:

-   Facial palsy
-   Visual changes→blindness
-   Coma

**Pathophysiology**: Disruption of the normal autoregulatory mechanisms of cerebral blood flow. The
inability of cerebral vasculature to constrict appropriately in response to the abrupt increase in
cerebral blood flow leads to cerebral hyperperfusion. Generally, short-acting antihypertensives are
preferred in the initial instance of treatment so that any potentially harmful drop in blood
pressure (which could lead to Posterior Reversible Encephalopathy Syndrome {PRES}) could be
reversed. Subsequently, long-acting agents could be used Sublingual nifedipine could cause a
precipitous drop in blood pressure so it is best avoided or should be used with extreme caution

Treatment outline:

-   Use Ianti-hypertensive drugs
-   Blood pressure should be brought down slowly to a desirable level (?stage I)by 48hrs (though not
    to normal levels) as follows:
    -   1/3 of total blood pressure reduction in 1st 12-hrs
    -   Next one-third of the subsequent 12-hrs
    -   Final one-third over 24-hrs
-   Alternatively, by a quarter within 6 hours, and the rest in the next 24-36hrs

Common preferred drugs:\
- Labetalol infusion\
- Na nitroprusside infusion - IV hydrallazine infusion

After achieving the desired blood pressure target, oral antihypertensives are then started
