---
title: "HIV"
author: Dr Anthony Enimil
---

## Definition

Human immunodeficiency virus (HIV) is an infection that attacks the body’s immune system,
specifically the white blood cells called CD4 cells. HIV destroys these CD4 cells, weakening a
person’s immunity against opportunistic infections, such as tuberculosis, fungal infections, severe
bacterial infections, and some cancers.1

## Incidence/prevalence

Globally, 39 million people were living with HIV in 2022 out of which 1.5 million were children
below 15 years. In Ghana, out of 354,927 people living with HIV in 2022, 7% (24,845) were children
below 15 years. There were 16,574 new HIV infections in 2022 out of which 17% (2,818) were children.
Mother-to-child transmission of HIV at 6 weeks in 2022 was 9.12% while the final MTCT rate at 18
months was 17.75%. In 2022, there were 21,439 adolescents (10-19 years) living with HIV out of which
1,791 were newly infected.2

## Aetiology

HIV is a retrovirus with two main subtypes namely HIV 1 and HIV 2. HIV-1 is the most common type of
HIV and accounts for 99% of all infections in Ghana, whereas HIV-2 is relatively uncommon (0.08%)
and less infectious. Ghanaians co-infected with HIV 1 and HIV 2 form 0.02% of total infections.
HIV-2 is mainly concentrated in West Africa and the surrounding countries. HIV-2 is less fatal and
progresses more slowly than HIV-1. Modes of HIV transmission are sexual (80% in Ghana) mainly
heterosexual but also same-sex; parenteral transmission (5%) examples include blood transmission,
shared needles, and needle stick accidents, and mother-to-child transmission (15%) of which
in-utero, intrapartum and postpartum accounts for 10-25%, 60-75%, and 10-20% respectively.

## Pathogenesis

HIV entry, the first phase of the viral replication cycle, begins with the adhesion of the virus to
the host cell and ends with the fusion of the cell and viral membranes with subsequent delivery of
the viral core into the cytoplasm. The intricate series of protein-protein interactions that
ultimately result in virus infection can be divided into several phases, some of which are essential
and others that may modulate the efficiency of the process.3

Infection with HIV starts without symptoms or ill-feeling and is accompanied by slight changes in
the immune system. This stage spans up to three months after infection until seroconversion where
HIV-specific antibodies can be detected in individuals following recent exposure. The outcome of
infection and duration of disease progression with clinical symptoms may vary greatly between
individuals, but often it progresses fairly slowly. It takes several years from primary infection to
the development of symptoms of advanced HIV diseases and immunosuppression.4 Although individuals
may look healthy during primary infection, the virus replicates in infected individuals' lymph nodes
and bloodstream. As a result, the immune system may get slowly damaged by the burst of viral load in
their bodies.5

## Signs and symptoms

Signs and symptoms develop when the immune system’s ability to fight the disease is compromised due
to viral replication and reduced CD4 cells.

### Early/ acute HIV

Acute HIV infection, also known as primary HIV infection, can cause a range of symptoms that can
begin a few days after exposure to the virus and last for a few days to several months

### Late chronic HIV

The late stage of HIV infection is AIDS (acquired immunodeficiency syndrome), which occurs when the
virus weakens the immune system.

### Staging of HIV

::: {#tbl-hiv-staging}
```{=html}
<table style="border-collapse:collapse;border:none;">
    <caption>HIV Staging</span></caption>
    <tbody>
        <tr>
            <td colspan="2" style="width: 450.8pt;border: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><strong><span style='font-family:"Times New Roman",serif;'>Stage 1</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Asymptomatic</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Generalised lymphadenopathy</span></p>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="width: 450.8pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><strong><span style='font-family:"Times New Roman",serif;'>Stage 2</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained persistent hepato-splenomegaly</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Recurrent or chronic upper respiratory tract infections (otitis media, otorrhoea, sinusitis, tonsillitis)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Herpes zoster</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Linear gingival erythema</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Recurrent oral ulceration</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Papular pruritic eruption</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Fungal nail infections</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Extensive wart virus infection</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Extensive Molluscum contangiosum</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained persistent parotid enlargement</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 225.4pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><strong><span style='font-family:"Times New Roman",serif;'>Stage 3</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained moderate malnutrition and not adequately responding to standard therapy</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained persistent diarrhoea (14 days or more)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained persistent fever (above 37.5&deg;C, intermittent or constant, for longer than one 1 month)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Persistent oral candidiasis (after first 6 weeks of life)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Oral hairy leukoplakia</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Lymph node tuberculosis</span></p>
            </td>
            <td style="width: 225.4pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><strong><span style='font-family:"Times New Roman",serif;'>Stage 3</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Pulmonary tuberculosis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Severe recurrent bacterial pneumonia</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Acute necrotising ulcerative gingivitis or</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>periodontitis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained anaemia (&lt;8g/dl), neutropenia (&lt;0.5x 10<sup>9</sup>/l) and chronic thrombocytopenia (&lt;50 x 10<sup>9</sup>/l).&nbsp;</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Symptomatic lymphoid interstitial pneumonitis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Chronic HIV-associated lung disease, including</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>bronchiectasis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 225.4pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0cm 5.4pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><strong><span style='font-family:"Times New Roman",serif;'>Stage 4</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Unexplained severe wasting, stunting or severe malnutrition not responding to standard therapy</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><em><span style='font-family:"Times New Roman",serif;'>Pneumocystis (jiroveci) pneumonia</span></em></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Recurrent severe bacterial infections (such as empyema, pyomyositis, bone or joint infection, and meningitis, but excluding pneumonia)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Chronic herpes simplex infection (orolabial or cutaneous of more than 1 month&rsquo;s duration or</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>visceral at any site)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Oesophageal candidiasis (or candidiasis of the trachea, bronchi or lungs)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Extrapulmonary tuberculosis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Kaposi sarcoma</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Cytomegalovirus infection (retinitis or infection of other organs with onset at age more than 1 month)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Central nervous system toxoplasmosis (after the neonatal period)</span></p>
            </td>
            <td style="width: 225.4pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0cm 5.4pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><strong><span style='font-family:"Times New Roman",serif;'>Stage 4</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>HIV encephalopathy</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Cytomegalovirus infection (retinitis or infection of other organs with onset at age more than 1 month)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Extrapulmonary Cryptococcosis, including meningitis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Disseminated non-tuberculous mycobacterial infection</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Progressive multifocal leukoencephalopathy</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Chronic cryptosporidiosis (with diarrhoea)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Chronic Isosporiasis</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Disseminated endemic mycosis (Extrapulmonary histoplasmosis, coccidioidomycosis, penicilliosis)</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>Cerebral or B-cell non-Hodgkin lymphoma</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>HIV-associated nephropathy or cardiomyopathy</span><span style='font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;line-height:150%;'><span style='font-family:"Times New Roman",serif;'>&nbsp;</span></p>
            </td>
        </tr>
    </tbody>
</table>
```
:::

## Investigations

Depending on signs and symptoms, a patient could be suspected of HIV infection and AIDS. Children
are then tested for HIV depending on their age.

### Newborn to \<18 months

Younger children (\< 18 months) who are exposed to HIV or are suspected of HIV should be tested at
any time they have symptoms of HIV disease. The preferred test is the DNA PCR which is done using
dried blood spots (DBS) taken from pricking the heel of a child onto filter paper. If the test is
positive, the child should be started on treatment, but a second confirmatory test must be done.
Infants born to HIV-positive mothers without symptoms are routinely tested within 6 weeks of birth,
at 9 months of age using DNA PCR. At 18 months such children are tested with antibody tests using a
“triple algorithm” as detailed below.

### 18 months and above

Should be tested using the “triple algorithm” when a patient is sequentially tested using first
response, Oraquick, and SD biofilm test. ALL three tests must be positive before a child is
confirmed HIV positive. @fig-HivTestAlgorithm below gives further information

```{mermaid}
%%| label: fig-HivTestAlgorithm
%%| fig-cap: "HIV testing algorithm for non-pregnant women and general population"
flowchart TD
    A(Screen with First response)-->B(Reactive First Response);
    A-->C(First Response non-reactive <br> Report HIV Negative);
    B-->D(Test with Oraquick <br> HIV 1&2);
    D-->E(If reactive to <br> both First Response <br> & Oraquick);
    D-->F(If First Response <br> was reactive but <br> not Reactive to Oraquick);
    E-->G(Confirm with SD Bioline);
    F-->H(Repeat both First <br> Response & Oraquick <br> sequentially);
    H-->I(Reactive to First <br> Response & Oraquick: <br> Confirm with SD Bioline);
    H-->J(If Non-reactive <br> to first response report <br> HIV Negative);
    G-->K(Reactive to First <br> Response, Oraquick <br> and SD Bioline <br> Report HIV-positive);
    G-->L(Reactive to First <br> Response & Oraquick <br> but non-reactive to <br> SD Bioline Report HIV <br> inconclusive. Retest in 14 days);
    H-->M(If reactive to First <br> Response but non-reactive <br> to Oraquick report <br> HIV Negative);
    I-->G
```

Baseline investigations are needed before initiating antiretroviral treatment/ monitoring of the
disease. These are listed in @tbl-hiv-investigations

```{r}
#| echo: false
#| message: false
#| tbl-cap: "Baseline investigations for HIV"
#| label: tbl-hiv-investigations

library(tidyverse)
tibble(
    Test = c(
        "Haematological", "Biochemistry", "","","","Routine", "", 
        "Respiratory", "", "", "Serological", "Immunological", 
        "Optional (Patient dependent)","", "", "", ""),
    Types = c(
        "Full blood count", 
        "Blood Urea Electrolytes and Creatinine", 
        "Liver Function tests", 
        "Fasting Blood Sugar", 
        "Cholesterol and lipid profile", 
        "Urinalysis (Urine R/E)", 
        "Stool R/E",
        "TB screening",
        "GeneXpert", 
        "Chest X-ray", 
        "Hepatitis B Surface antigen",
        "CD4",
        "Histology on skin and lymph node biopsy",
        "Kidney biopsy",
        "Screening for STIs",
        "Pap smear, HPV DNA",
        "Abdominal Ultrasound")
    ) %>% 
    gt::gt() %>%
    gt::tab_options(
        data_row.padding = gt::px(2),
        table.font.size = 14) %>% 
    gt::tab_style(
            style= gt::cell_text(weight = "bold"), 
            locations = gt::cells_body(columns = Test)) %>% 
    gt::opt_stylize(5)
```

When children are on treatment viral load tests are done regularly. This is done to detect early
virological failure. When highly active antiretroviral therapy (HAART) is started, the first viral
load test is done at 6 and 12 months. If there is virological suppression, then monitoring is done
yearly. The table below outlines what to do with various viral load cut-offs and actions to take


```{mermaid}
%%| label: fig-viral-load-monitoring
%%| fig-cap: "Treatment Monitoring Algorithm"

flowchart TD
    A(Routine viral load monitoring for <br> early detection of treatment failure: <br> Obtain and review results by <br> 6 months after ART initiation., 12 <br> months after ART initiation and <br> yearly thereafter)-->B(Undetectable  <=50 copies /ml);
    A-->C(Viral load <br>  >50 to <= 1000 copies /ml);
    A-->D(Viral load <br> >1000 copies /ml);
    B-->F(Maintain ARV drug regimen);
    C-->G(Provide enhanced adherence <br> counselling: Repeat viral load <br> testing after 3 months);
    D-->G;
    D-->E(if NNRTI regimen switch to <br> the appropriate regimen);
    G-->H(Undetectable  <=50 copies /ml);
    G-->I(Viral load  >50 to <= 1000 copies /ml);
    G-->J(Viral load >1000 copies /ml);
    H-->K(Maintain ARV drug regimen);
    I-->L(Maintain ARV drug <br> regiment but continue<br> enhanced adherence counselling <br> and repeat viral load <br> testing after 3 months);
    J-->M(Switch to the <br> appropriate regimen)
```

## Treatment

Before commencing HAART for any child or adolescent, counsel the caregiver and the child if old
enough to appreciate the counselling

### Infants born to HIV-positive mothers (post-exposure prophylaxis)

All newborns of HIV-positive mothers are called HIV-exposed babies. These babies should be given
antiretroviral prophylaxis namely nevirapine and zidovudine daily starting from birth (within 24
hours) for 3 months. At week 6, infants should be started on cotrimoxazole daily till HIV infection
is ruled out at 18 months. At any point in time when a child tests positive for HIV, treatment with
cotrimoxazole should be continued for a longer duration till the child’s immune system is fully
re-constituted and appropriate for age. The best marker is appropriate CD4 for age. In the absence
of CD4 testing, the child should be virologically suppressed with no evidence of clinical
disease.\@borges-lujan2022

### Treatment of HIV infection

Counselling caregivers and children is a must before initiating HAART. Emphasise should be on HAART
being a lifelong treatment. Adherence counselling should be integrated into clinical care. The HAART
consist of 2 Nucleos(t)ide Reverse Transcriptase Inhibitor (N(t)RTI plus Non-nucleoside Reverse
Transcriptase Inhibitor (NNRTI) or Integrase Strand Transfer Inhibitor (INSTI) or Protease Inhibitor
(PI). HAART regimen should have a minimum of three ARVs. The table below shows the types of ARVs
available in Ghana

::: {#tbl-oopo}
```{=html}
<table style="border-collapse: collapse; border: none;">
<caption>Antiretroviral Groups</span></caption>
<tbody>
<tr>
<td style="width: 92.0pt; border: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: justify; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Group 1</span></strong></p>
</td>
<td style="width: 70.7pt; border: solid windowtext 1.0pt; border-left: none; padding: 0cm 5.4pt 0cm 5.4pt;" width="94">
<p style="text-align: justify; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Group 2</span></strong></p>
</td>
<td style="width: 253.8pt; border: solid windowtext 1.0pt; border-left: none; padding: 0cm 5.4pt 0cm 5.4pt;" colspan="3" width="338">
<p style="text-align: justify; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Group 3</span></strong></p>
</td>
</tr>
<tr>
<td style="width: 92.0pt; border: solid windowtext 1.0pt; border-top: none; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">N(t)RTI</span></strong></p>
</td>
<td style="width: 70.7pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="94">
<p style="text-align: center; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">NRTI</span></strong></p>
</td>
<td style="width: 83.7pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="112">
<p style="text-align: center; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">NNRTI</span></strong></p>
</td>
<td style="width: 77.95pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="104">
<p style="text-align: center; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">INSTI</span></strong></p>
</td>
<td style="width: 92.15pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">PI</span></strong></p>
</td>
</tr>
<tr>
<td style="width: 92.0pt; border: solid windowtext 1.0pt; border-top: none; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Abacavir (ABC)</span></p>
</td>
<td style="width: 70.7pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="94">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Lamivudine (3TC)</span></p>
</td>
<td style="width: 83.7pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="112">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Efavirenz (EFV)</span></p>
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Weight &gt; 10 kg</span></p>
</td>
<td style="width: 77.95pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="104">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Dolutegravir (DTG)</span></p>
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Weight &gt;3 kg</span></p>
</td>
<td style="width: 92.15pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Ritonavir boosted Lopinavir (LPV/r)</span></p>
</td>
</tr>
<tr>
<td style="width: 92.0pt; border: solid windowtext 1.0pt; border-top: none; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Zidovudine (AZT)</span></p>
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">(Hb&gt; 8 g/dl)</span></p>
</td>
<td style="width: 70.7pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="94">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Emtricitabine (FTC)</span></p>
</td>
<td style="width: 83.7pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="112">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Nevirapine (NVP)</span></p>
</td>
<td style="width: 77.95pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="104">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Raltegravir (RAL)</span></p>
</td>
<td style="width: 92.15pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Ritonavir boosted Atazanavir (ATV/r)</span></p>
</td>
</tr>
<tr>
<td style="width: 92.0pt; border: solid windowtext 1.0pt; border-top: none; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Tenofovir (TDF)</span></p>
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">(Renal disease)</span></p>
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Weight=&gt;30 kg</span></p>
</td>
<td style="width: 232.35pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" colspan="3" width="310">
<p style="text-align: center; line-height: 115%;"><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Read around the main side effects/contraindications of each ARV</span></strong></p>
</td>
<td style="width: 92.15pt; border-top: none; border-left: none; border-bottom: solid windowtext 1.0pt; border-right: solid windowtext 1.0pt; padding: 0cm 5.4pt 0cm 5.4pt;" width="123">
<p style="text-align: center; line-height: 115%;"><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Times New Roman',serif;">Ritonavir boosted Darunavir (DRV/r)</span></p>
</td>
</tr>
</tbody>
</table>
```
:::

HAART combination can be made easy by choosing one ARV from each group.

::: {#tbl-alternative-arv}
```{=html}
<table style="border: none;border-collapse:collapse;">
    <caption>Preferred and alternative first-line ART regimens for adolescents, children and neonates</span></caption>
    <tbody>
        <tr>
            <td style="border: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 29.5pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Populations</span></strong></p>
            </td>
            <td style="width: 128.3pt;border-top: 1pt solid black;border-right: 1pt solid black;border-bottom: 1pt solid black;border-image: initial;border-left: none;padding: 0.75pt 5.4pt 0cm;height: 29.5pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Preferred first-line</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>regimen</span></strong></p>
            </td>
            <td style="width: 99.2pt;border-top: 1pt solid black;border-right: 1pt solid black;border-bottom: 1pt solid black;border-image: initial;border-left: none;padding: 0.75pt 5.4pt 0cm;height: 29.5pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Alternative first-line</span></strong></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>regimen</span></strong></p>
            </td>
            <td style="width: 173.2pt;border-top: 1pt solid black;border-right: 1pt solid black;border-bottom: 1pt solid black;border-image: initial;border-left: none;padding: 0.75pt 5.4pt 0cm;height: 29.5pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Special circumstances</span></strong></p>
            </td>
        </tr>
        <tr>
            <td style="border-right: 1pt solid black;border-bottom: 1pt solid black;border-left: 1pt solid black;border-image: initial;border-top: none;padding: 0.75pt 5.4pt 0cm;height: 97.25pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Adolescents&nbsp;</span></strong></p>
            </td>
            <td style="width: 128.3pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 97.25pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF + 3TC (or FTC) + DTG</span></p>
            </td>
            <td style="width: 99.2pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 97.25pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF + 3TC + EFV 400mg</span></p>
            </td>
            <td style="width: 173.2pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 97.25pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF + 3TC (or FTC) + EFV600mg</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>AZT + 3TC + EFV 600 mg</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF + 3TC (or FTC) + PI/r</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF + 3TC (or FTC) + RAL</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>ABC + 3TC + DTG</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF + 3TC (or FTC) + PI/r</span></p>
            </td>
        </tr>
        <tr>
            <td style="border-right: 1pt solid black;border-bottom: 1pt solid black;border-left: 1pt solid black;border-image: initial;border-top: none;padding: 0.75pt 5.4pt 0cm;height: 69.6pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Children</span></strong></p>
            </td>
            <td style="width: 128.3pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 69.6pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>ABC + 3TC + DTG</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>&nbsp;</span></strong></p>
            </td>
            <td style="width: 99.2pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 69.6pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>ABC + 3TC + LPV/r</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>TDF+ 3TC (or FTC) + DTG</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>&nbsp;</span></p>
            </td>
            <td style="width: 173.2pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 69.6pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>ABC + 3TC + EFV&nbsp;</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>ABC + 3TC + RAL</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>AZT + 3TC + EFV&nbsp;</span></p>
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>AZT + 3TC + LPV/r (or RAL)</span></p>
            </td>
        </tr>
        <tr>
            <td style="border-right: 1pt solid black;border-bottom: 1pt solid black;border-left: 1pt solid black;border-image: initial;border-top: none;padding: 0.75pt 5.4pt 0cm;height: 27.45pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><strong><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>Neonates</span></strong></p>
            </td>
            <td style="width: 128.3pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 27.45pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>AZT (or ABC) + 3TC + RAL(or DTG)</span></p>
            </td>
            <td style="width: 99.2pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 27.45pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>AZT + 3TC + NVP</span></p>
            </td>
            <td style="width: 173.2pt;border-top: none;border-left: none;border-bottom: 1pt solid black;border-right: 1pt solid black;padding: 0.75pt 5.4pt 0cm;height: 27.45pt;vertical-align: top;">
                <p style='margin:0cm;font-size:16px;font-family:"Aptos",sans-serif;text-align:center;line-height:115%;'><span style='font-size:13px;line-height:115%;font-family:"Times New Roman",serif;'>AZT + 3TC + LPV/r</span></p>
            </td>
        </tr>
    </tbody>
</table>
```
:::

### Side effects of main ARVS

Depending on the type of HAART, children may experience different side effects. Regular clinical and
laboratory monitoring will be needed to identify side effects early. There are alternative ARVs in
each group to substitute if a child on HAART experiences a major side effect.

::: {#tbl-arv-toxicities}
|                                   |                                                                                                                                                                                                                                                      |
|---------------------|-------------------------------------------------------------------------------|
| **Haematological toxicity**       | Drug-induced bone marrow suppression is most commonly seen with AZT (anaemia, neutropenia).                                                                                                                                                          |
| **Mitochondrial Dysfunction**     | Primarily seen with the NRTI drugs, including lactic acidosis, hepatic toxicity, pancreatitis, peripheral neuropathy, lipoatrophy, myopathy                                                                                                          |
| **Renal Toxicity**                | Renal tubular dysfunction is associated with Tenofovir (TDF). ATV/r can also cause nephrolithiasis.                                                                                                                                                  |
| **Other Metabolic Abnormalities** | More common with PIs and INSTIs. Include hyperlipidaemia, fat accumulation, insulin resistance, diabetes and osteopenia. Lipodystrophy is also associated with Zidovudine. The risk of cardiovascular events with Abacavir (ABC) is still debatable. |
| **Allergic Reactions**            | Skin rashes and hypersensitivity reactions, are more common with the NNRTI drugs but also seen with certain NRTI drugs, such as ABC and some PIs.                                                                                                    |
| **Hepatic Toxicity**              | Liver enzyme elevation with DTG especially in patients with HBV or HCV co-infection. DRV/r also causes liver enzyme elevation                                                                                                                        |
| **Muscular Toxicity**             | Muscle weakness and sometimes rhabdomyolysis are seen with RAL                                                                                                                                                                                       |

: Common ARV toxicities
:::

## Complications

The main complication of HIV infection is the progression to AIDS when HAART is not initiated. Those
children on treatment with non-adherence or poor adherence to HAART can ultimately develop AIDS.
This will be the consequence of reduced CD4 cell count and increased viral load

## Prognosis

Patients who start treatment early before immune dysgenesis and are virologically controlled have a
life expectancy like an HIV-negative individual

## Differential diagnosis

Acute HIV infection may be asymptomatic or may cause a mononucleosis-like syndrome. It should be
differentiated from similar diseases that cause fever, fatigue, sore throat, myalgia, and
lymphadenopathy such as acute toxoplasmosis, acute CMV/EBV infections, and acute viral hepatitis

## Further reading

Consolidated Guidelines for HIV care in Ghana

## Sample case scenarios

1.  A 10-year-old boy presented to your facility with skin rashes, weight loss, fever, and cough of
    3 months duration. On examination, he was semi-conscious. Chest X-ray was suggestive of
    pulmonary tuberculosis. CSF from Lumber puncture was positive on GeneXpert
    a.  How would you confirm HIV in this child?
    b.  What is the appropriate WHO clinical staging
2.  A 5-year-old boy has recently been diagnosed with HIV. You intend to start antiretrovirals. He
    weighs 25 kg with Hemoglobin of 6 gm/dl.  His renal and liver function is normal. Which option
    will be your best HAART?
    a.  ABC/3TC/EFV
    b.  ABC/3TC/DTG
    c.  AZT/3TC/LPV/r
    d.  TDF/3TC/EFV
3.  A 15-year-old male drug addict, newly diagnosed with HIV. He weighs 35 kg. The renal and liver
    functions are normal. Based on the history, what additional questions will you ask? What
    additional test would you do?
    a.  Propose ARVs
4.  A 6-month-old was admitted to your facility with a fever, poor weight gain and oral thrush. HIV
    antibody test came up positive in both mother and infant
    a.  Does this HIV antibody test confirm HIV in the child?
    b.  What other tests are required in this child?
5.  A 2-month-old newly diagnosed with HIV. Weight 5kg, Hb=12 g/dl normal renal and kidney
    function.     
    a.  Suggest ARVs for treatment

## **Answers to sample questions**

1.  It is important to know the duration of the other symptoms if they are beyond 3 months. Ask
    about interventions, facilities visited and what was done for the patient. The top three
    possibilities are HIV/AIDS, Malignancy and tuberculosis. Malignancy should be ruled out (REFER
    TO ONCOLOGY LECTURES). Tuberculosis is confirmed in this child. Since HIV is a risk factor for
    developing TB, it is right to think of HIV in this child. Remember HIV is a family disease.
    Parents and other siblings MUST also be screened if they exist.

    To diagnose HIV test, this child must have positive tests on all tests using the “triple
    algorithm” namely first response, Oraquick, and SD bioline.

    This child has confirmed Pulmonary TB. PTB is airborne and therefore there is the need to screen
    close contacts. This will help identify the index case and put in necessary screening tests.
    Those who have the disease are treated while those exposed without the disease will need TB
    preventive therapy.

    This child’s HIV test was positive. He has both pulmonary TB and TB meningitis. Referring to the
    notes on WHO clinical staging, PTB is stage 3 while TB Meningitis (TBM) is stage 4. This child
    therefore has clinical stage 4

    Remember that this child has an opportunist infection (TB). To prevent Immune Reconstitutive
    Inflammatory Syndrome (IRIS), this child has to start TB treatment before starting HAART, for
    PTB HAART is started preferably 2 weeks after TB medication. For TBM, HAART should be started
    4-6 weeks after initiating TB medications.

    Note: Drug-drug interaction occurs between some ARVs and rifampicin. Dolutegravir,
    lopinavir/ritonavir, and nevirapine should be doubled when administered simultaneously with
    rifampicin. When TB treatment ends, extend the duration of the double dose of the ARVs for 2
    weeks before reducing the dose to the expected age and weight of the children.

2.  In deciding on the best HAART, an ARV should each be selected from groups 1,2 and 3. From group
    1, the only feasible option is abacavir because HB is \< 8g/dl and weight is \< 30 kg(AZT and
    TCF cannot be used). Under group 2, either 3TC or FTC are possible but 3TC is readily available.
    Under group 3, DTG will be the best option because EFV has a lower resistance barrier and high
    community resistance. LPV/r is plausible but twice daily regimen makes compliance more
    difficult. The best option will be ABC/3TC/DTG (option b is the best choice)

3.  Being a drug addict, he may be using intravenous injection which increases his risk of being
    infected with hepatitis B or hepatitis C. Again, he may be having sexual partners exposing him
    to STI. He, therefore, has to be investigated for hepatitis B/C, full blood count, and screened
    for other STIs. The choice of HAART will have to factor in hepatitis B status. TDF can be given
    because he weighs more than 30 kg and renal function is normal. Based on the previous
    explanation, TDF/3TC/DTG is the best choice. This option comes as a Fixed dose combination so he
    will take just 1 tablet daily, improving compliance among adolescents. Should the adolescent be
    Hepatitis B positive, TDF/3TC are also active against hepatitis B. Adolescents should be
    referred for appropriate services if there are other co-morbidities. Referral to a clinical
    psychologist will also be needed because he is addicted to drugs

4.  Antibodies are IgG and cross the placental to the baby. Newborns testing positive using antibody
    tests might be maternally transmitted. Antibody tests do not confirm HIV in children below 18
    months. These antibodies are expected to disappear by 18 months. The recommended test for a
    6-month-old baby is a DNA PCR test (refer to above). Other tests and timelines if the baby is
    negative at 6 months, are at 9 months (DNA PCR) and 18 months (antibody test)

5.  For a 2-month-old, an Hb of 12 is low; therefore, AZT will not be a good option. The HAART of
    choice is ABC/3TC/DTG

## **Self-assessment questions**

1.  A 15-year-old takes HAART which he thinks are vitamins for SCD. How would you disclose his true
    status to him?
2.  A 17-year-old adolescent girl is about to start HAART. Explain the content of your counselling.
