---
title: "Paediatric Tuberculosis"
author: Dr Anthony Enimil
date: 2024-06-04
---

## Definitions

Infection with Mycobacterium tuberculosis usually results from inhaling infected droplets produced
by someone who has Pulmonary Tuberculosis (TB) and is coughing. The most infectious source cases are
those with sputum smear-positive disease. The closer the contact with this source case, the greater
the exposure and the greater the risk of getting infected with tuberculosis.

**TB infection** occurs when a person carries the Mycobacterium tuberculosis bacteria inside the
body. Many people have TB but are well. A positive tuberculin skin test (TST) suggests infection but
a negative TST does not exclude the possibility of infection.

**TB disease** occurs in someone with TB infection when the bacteria inside the body start to
multiply and become numerous enough to damage one or more organs of the body. This damage causes
clinical symptoms and signs. This is referred to as “tuberculosis” or active disease.

**Close contact** is defined as living in the same household as, or in frequent contact with (e.g.
caregiver, school staff), a source case with PTB.

**Multidrug-resistant TB (MDR-TB)** is caused by M. tuberculosis strains that are resistant to both
*isoniazid* and rifa*mpicin*.

**Pre-extensively drug-resistant TB (Pre-XDR)**: TB caused by M. tuberculosis strains that fulfil
the definition of multidrug-resistant TB (MDR-TB) or rifampicin-resistant TB (RR-TB) and that are
also resistant to any fluoroquinolone.

**Extensively drug-resistant TB (XDR-TB):** TB caused by M. tuberculosis strains that fulfil the
definition of MDR/RR-TB and that are also resistant to any fluoroquinolone and at least one
additional Group A medicine. (bedaquiline and linezolid)

## Incidence/prevalence

According to the 2023 WHO global TB report; globally, a total of 10.6 million people fell ill with
TB in 2022 of which children less than 15 years accounted for 12%. According to WHO estimates for
2022, there were 44,000 estimated incident cases in Ghana. Of this number, Ghana notified 16,526
cases of which 10% were expected to be paediatric (0-14yrs). However, 5% of paediatric cases were
notified.

## Aetiology

The Mycobacterium tuberculosis complex (MTBC) constitutes a significantly genetically similar group
of bacteria that cause tuberculosis in various hosts. They are rod-shaped, acid-base-fast, aerobic,
slow-growing intracellular pathogens that destroy phagosomal cells to maintain and evade the immune
system. The major MTBC pathogenic mycobacteria species include M. tuberculosis, M. bovis, M.
africanum, and M. microti.[@zhang2022]

## Pathogenesis

Following the M. tuberculosis transmission to a new host, the bacilli enter the lung and get
ingested by macrophages. Further, immune cells are recruited to wall off the infected macrophages,
forming granuloma, the hallmark of TB. Healthy individuals remain latently infected, and the
infection is kept at bay at this stage, but it is prone to the risk of reactivation. As the
granuloma develops, the bacilli emerge from the macrophages. When the reactivation occurs, M. tb
proliferates, the bacterial load becomes overwhelmingly high, and the granuloma ruptures,
disseminating the bacteria to the airways. The bacilli are then expectorated as contagious aerosol
droplets, restarting the cycle, and infecting other individuals.[@alsayed2023]

## Signs and symptoms

It is important to understand the risk for TB infection and TB disease. Taking the history from
children and caregivers must include questions on risk factors.

**For an infection to occur, there are certain factors**:

1.  Contact with source case (Close contact and duration of contact)
2.  Source case (Smear positivity: smear positive is more infectious; Cavitation on Chest X-ray:
    more infectious)
3.  Increased exposure (Living in high TB endemic areas; children of families living with
    [HIV](id-hiv.qmd))

**Factors affecting TB disease**:

1.  Young age ( 2 years and below)
2.  [HIV](id-hiv.qmd) infection
3.  Other immunosuppression (Malnutrition, Post-measles)
4.  Not BCG vaccinated (Risk of disseminated TB or severe TB disease)

**Pulmonary Tuberculosis**

***History –The major considerations***

Make every effort to look for the close contact or the household contact who is the source of the
infection. It is helpful to note that close contact may be at school in a classroom, dormitory/
school bus, or church. Sometimes, it may be someone who frequently visits the child’s home or a
caregiver. In childhood, it may take between 3 months to 2 years from the time of exposure to
develop TB disease.

**History of symptoms suggestive of TB**

More commonly children with TB will present with the following symptoms:

1.  Cough of any duration or progressive non-remitting cough which may be dry or wet.
2.  Fever (persistent or unexplained)
3.  Lethargy/reduced playfulness/less active
4.  Poor weight gain or weight loss or very low weight (failure to thrive), flattened growth curve
    is a very sensitive marker of disease. More specifically it is important to plot the measurement
    and compare it to previous charts on the growth charts in the child health record booklet
5.  Night sweat. Since most children sweat at night, it is usually difficult to establish this
    symptom.

**Physical Examination** **(Some clinical findings suggestive of PTB)**

***General Examination***

1.  Fever- Temperature that remains persistently high or irregular \>37.5 (fever)
2.  Weight- (confirm poor weight gain, recent weight loss): the weight should be plotted on the
    child’s growth curve, and any child who “falls off” or is unable to maintain their usual line of
    growth should be considered as having possible TB
3.  Length/Height is needed to determine the weight-for-length/height Z-scores (\<-3 Z indicates
    severe wasting)
4.  MUAC -Middle upper arm circumference of \< 12.5 cm
5.  Respiratory rate - (fast breathing) depends on the patient's age. (Children 0-2 months above
    60cpm, 3 months to 12 months more than 50 CPM and 1-5 years more than 40 CPM)
6.  Signs of respiratory distress are not specific to TB but must raise the index of suspicion e.g
    Low oxygen saturation, stridor, and wheezes

**Physical signs suggestive of Extra Pulmonary TB (EPTB) include**:

1.  Enlarged cervical lymph nodes which are not painful with or without fistula formation – TB
    lymphadenopathy;
2.  Presence of spinal kyphosis (angular swelling) – spinal TB (“gibbous”);
3.  Signs of non-acute meningitis with poor response to antibiotic treatment and/or with raised
    intracranial pressure – TB Meningitis;
4.  Pleural effusion, especially one-sided dullness with pleuritic pain in a child who is not
    acutely ill – pleural TB;
5.  Pericardial effusion, distant or muffled heart sounds or signs of new-onset heart failure –
    pericardial TB;
6.  Non-acute distended abdomen with or without ascites – abdominal TB;
7.  Non-tender swollen joints with painful or abnormal gait – osteoarticular TB.

## Investigations

In addition to a detailed history and careful physical examination, all children suspected to have
TB will require additional investigations. Investigations commonly used are grouped into the
following categories.

1.  Bacteriological investigations
2.  Radiologic investigations and
3.  Immunologic investigations.

### Bacteriological investigations

**Xpert MTB/RIF Assay** is the recommended first-line investigation for diagnosing TB in children.
Results are rapid and determine if the patient has a drug-sensitive or resistant organism. Various
specimens may be collected, including expectorated sputum, induced sputum, gastric aspirate,
bronchoalveolar lavage, transbronchial biopsies, pleural aspirate urine, blood, cerebrospinal fluid
tissue and, more recently, stool. Other modalities for confirming TB are smear microscopy and TB
cultures.

### Radiologic investigations

Children often have paucibacillary TB and therefore bacteriological yields are low. Various imaging
modalities can be suggestive of TB. Chest X-ray is the most frequently used radiological imaging.
The presence of hilar lymphadenopathy (@fig-id-cxr-ptb), effusions, and cavitations could all
support the diagnosis of TB in children. Ultrasound, CT scan, and MRI all have roles in suspected
extrapulmonary TB.

![Chest X-ray showing perihilar lymphadenopathy suggestive of
TB](images/id-cxr-ptb.jpg){#fig-id-cxr-ptb fig-alt="CXR showing PTB"
fig-align="center" width="351"}

### Immunologic investigations

Immunological tests provide evidence for TB infection but not TB disease. Two tests are widely used
namely the *Tuberculin skin test* and the *interferon-gamma release assay*.

## Treatment 

### Antituberculous medications

There are two types of treatment namely *TB disease treatment* and *TB preventive therapy.* The
Paediatric TB Medicines comprises of 3 different formulations as follows:

1.  Rifampicin + Isoniazid + Pyrazinamide (RHZ) 75/50/150 mg
2.  Ethambutol (E) 100 mg 3. Rifampicin + Isoniazid (RH) 75/50 mg

Every child receives 2RHZE ( 2 months intensive phase)/4RH (4 months continuation phase) for all
forms of TB except TB meningitis and osteoarticular TB where the continuation phase is extended for
10 months (10 RH). For non-severe TB (refer to further reading) 2RHZE/2RH regimen can be applied.

***Note:***

Corticosteroids are often used as an adjunct in the treatment of these forms of TB to prevent
complications. These include TB Meningitis; TB Pericarditis; and Pott disease/ TB Spondylitis.
Pleural diseases, and Endobronchial TB\
Pyridoxine (Vitamin B6) supplement is necessary in some patients to prevent peripheral neuropathy
but recommended in ALL [HIV](id-hiv.qmd)-infected persons and severely acute malnourished patients
on isoniazid

### Major side effects 

Potential side effects of TB medications are:

1.  Rifampicin: Orange-colored urine, saliva or tears, jaundice
2.  Pyrazinamide: GI disturbances, hepatotoxicity
3.  Ethambutol: GI disturbances, blurred vision
4.  Isoniazid: numbness and tingling in the extremities, GI disturbances, rash

### TB Preventive Therapy

Every person living with [HIV](id-hiv.qmd) should be given TB preventive therapy (TPT) after
screening and ruling out active TB disease. Other categories of children requiring TPT after ruling
out TB disease are:

1.  Newborns of mothers with TB,
2.  All Children exposed to an index case with sputum-positive TB,
3.  Long-term steroids, and immunocompromised children.

If a patient develops TB disease, the patient should be investigated, and treatment changed from TPT
to full treatment. There are four(4) options for TPT in children:

1.  Rifapentine + Isoniazid- weekly for 3 months
2.  Rifampicin + isoniazid – daily for 3 months
3.  Rifampicin- daily for 4 months
4.  Isoniazid only – daily for 6 months

## Complications 

The most common complication is chronic lung disease. TB can affect any part of the body including
the brain, spine and therefore can cause other complications such as stroke, abscesses, impaired
growth and so forth.

## Prognosis

With early identification and treatment, the prognosis is good.

## Differential diagnosis 

Common differentials are bacterial pneumonia, atypical pneumonia, brucellosis, bronchogenic
carcinoma, [HIV](id-hiv.qmd), and Hodgkin lymphoma

## Further readings 

[WHO consolidated guidelines on tuberculosis: module 5: management of tuberculosis in children and
adolescents](https://www.who.int/publications/i/item/9789240046764)

[WHO operational handbook on tuberculosis: module 5: management of tuberculosis in children and
adolescents](https://www.who.int/publications/i/item/9789240046832)

## Sample case scenarios

**Question**

1.  A mother delivers a newborn at 40 weeks gestation. Within the last 4 weeks of pregnancy, she
    started coughing. She bought cough syrup and amoxicillin at a dispensary. Her coughing got
    severe and she noted weight loss. At week 39, she visited the hospital and was diagnosed with TB
    (GeneXpert MTB positive and RIF sensitive). She was started on treatment immediately. She lives
    in a single room with her 3 other children who are 2 years, 8 years, and 10 years respectively
    who were all clinically well except the 2 years old who weighed 8 kgs.
    1.  Identify risks of infection for the children
    2.  Identify risks of disease in children
    3.  How would you approach the management of the children

**Answers**

a.  The risks of infection in the above scenario are sputum-positive MTB on GeneXpert tests and the
    single room is occupied by a single mother and her children.
b.  The risk of TB disease will be in the newborn and the 2-year-old sibling who is already failing
    to thrive. If the mother has [HIV](id-hiv.qmd) or the children are not immunised with BCG, that
    would also be a risk factors for disease.
c.  All the children have been exposed to TB through a close contact, who happens to be their
    mother. The mother has to be tested for [HIV](id-hiv.qmd). If she is positive, all the children
    should also be tested. All the children would have to be screened for TB. The newborn should
    ideally not be given BCG vaccine but put on TPT if TB disease is excluded. The recommended TPT
    will depend on the [HIV](id-hiv.qmd) status of the newborn, but Isoniazid is an option for 6
    months. After 6 months of INH, if there is no evidence that the newborn has been exposed to TB
    (Mantoux testing), the child can be given BCG vaccine. If the newborn has the disease, then full
    TB treatment should be given. The 2-year-old weighs 8 kg which is evidence of weight faltering.
    Plot the weight for age on the Z-score. Do other investigations such as Chest X-ray, stool for
    Xpert, and [HIV](id-hiv.qmd) testing. If the clinical, bacteriological, and imaging are
    suggestive of TB, treat the 2-year-old. If [HIV](id-hiv.qmd) is positive, remember to adjust the
    dose of ARVs that interact with rifampicin during TB treatment. If the screening of the 8 and 10
    years is normal, then put them on TPT, otherwise treat them

**Self-assessment questions**

1.  A 5-year-old boy diagnosed with TB and started on RHZE complained to his mother that he finds it
    difficult to see clearly what his school teacher has projected in class. Which of the following
    medications is likely responsible?
    a.  Isoniazid
    b.  Pyrazinamide
    c.  Ethambutol
    d.  Rifampicin
2.  Explain why bacteriological yield from children with suspected PTB is often very low.
