---
title: "Fragile X Syndrome"
author: "Dr. Joshua Sarkodie-Addo"
---

## Definition

Fragile X syndrome, previously known as Martin-Bell syndrome or marker X syndrome is the commonest
cause of X-linked intellectual disability and constitutes about 30% of all X-linked learning
disabilities as well as emotional problems ranging from mood instability to autism. Prevalence
varies according to the method of diagnosis but has been estimated at 1;4000 in males and 1;6000 in
females but may rise to 1:2000 in the general population when mildly affected individuals are
included.

## Genetics

It is an X-linked dominant disorder with variable expressivity and reduced penetrance. Fragile X
syndrome (FXS) was the first of a group of genetic conditions called trinucleotide repeat expansion
disorders. The FMR1 gene responsible for FXS encodes a protein called FMRP that is important for
brain development. When a female carries this premutation, it usually expands to a full mutation of
more than 200 CGG repeats in her offspring. The variable clinical phenotypes arise from a deficiency
or complete absence of FRMP and correlate with the size of the expansion. Note that point mutations,
deletions and missense mutations can also result in FXS.

## Clinical features

Presentation depends on the sex, age, mutation state (full mutation vs premutation), degree of
methylation, magnitude of FMRP deficit and mosaicism. Females tend to have milder expression.
Features may be classified into physical and cognitive aspects.

### Full mutation

1.  Physical
    a.  Facial features: Elongated face, high arched palate, large, cupped ears
    b.  Connective tissue anomalies: Mitral valve prolapse, aortic root dilatation, scoliosis, flat
        feet, and hyperflexible joints.
    c.  Other features: Hypotonia (infancy), macroorchidism (commonly post-pubertal), seizures,
        recurrent otitis media, strabismus, and refraction errors.
2.  Cognitive features
    a.  Intellectual disability and developmental delay
    b.  Autism 20-0%
    c.  ADHD 80%
    d.  Anxiety (70-100%)

### Permutation:

Affected females have been noted to develop premature ovarian failure, Fragile X-associated
tremor-ataxia syndrome (FXTAS) occurs in later life along with other neurocognitive defects.

## Associations

Fragile X syndrome is associated with autism spectrum disorders and ADHD. Obsessive-compulsive
behaviour has also been noted. Others include Obstructive sleep apnoea, and urinary tract anomalies
eg. Vesicoureteral reflux.

## Investigations

Early diagnosis is important for timely genetic counselling. Genetic testing for FMR1 DNA analysis
is the recommended investigation. A combination of PCR (measures CGG repeats) and Southern blot of
genomic DNA (determines methylation status) yields a sensitivity of 99%. Other investigations may be
required for certain features of the disease e.g. an Echocardiogram for mitral valve prolapse.

## Treatment

There is currently no cure for FXS. A variety of interventions are employed which work
synergistically in ameliorating the symptoms. These include.

-   Counselling (including genetic counselling) and testing of family members.
-   Psychopharmacology
    -   ADHD – stimulants eg. Methylphenidate
    -   Anxiety and compulsive behaviours – antidepressants eg. SSRIs
    -   Mood instability, aggression – antipsychotics eg. Risperidone
    -   Seizure control eg. Carbamazepine, valproate. Phenytoin and phenobarbitone are not
        recommended.
-   Speech and language therapy.
-   Motor therapy
-   Individualized educational plans
-   Health surveillance
-   Behaviour interventions tailored to maximise functioning. As such treatment requires a
    multidisciplinary approach.

## Complications

Strongly associated with the symptoms of the condition eg. Chronic otitis media and Epilepsy.

## Notes on Counselling 

It is important to note that life expectancy is the same as in the general population though quality
of life varies depending on the associated features and degree of intellectual disability.
Reproductive considerations must also be discussed: Males with full mutations are infertile, males
with premutation are fertile carriers, Females with full mutation are fertile, and females with
premutation have impaired fertility consequent from premature ovarian failure.
